import { describe, expect, it } from 'vitest'
import { FACTORY_BUNDLES, bundleSuggestions, cadetReadiness, requirementAvailability, searchCadets, validateBundle, validateCadet, validateRequirement } from './domain'
import type { CadetProjection, StillNeededProjection } from '../distributed/types'

const cadet: CadetProjection = { cadetId: 'cadet_opaque', fullName: 'Jordan Rivera', gender: 'Female', nsLevel: 'NS2', status: 'ACTIVE', sizes: { shoes: '10' }, currentProperty: [], createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z', version: 1, appliedEventIds: [] }
const need: StillNeededProjection = { requirementId: 'need_1', cadetId: cadet.cadetId, itemId: 'shoe', displayLabel: 'Black Oxfords', size: '10', quantityNeeded: 2, quantityFulfilled: 0, status: 'OPEN', firstNeededAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z', source: 'MANUAL', version: 1, appliedEventIds: [] }

describe('Stage 3A cadet and readiness domain', () => {
  it('validates complete cadets and rejects invalid values', () => { expect(() => validateCadet(cadet)).not.toThrow(); expect(() => validateCadet({ ...cadet, fullName: ' ' })).toThrow(/name/); expect(() => validateCadet({ ...cadet, gender: 'X' as 'Male' })).toThrow(/Gender/); expect(() => validateCadet({ ...cadet, nsLevel: 'NS5' as 'NS1' })).toThrow(/NS level/) })
  it('searches first, last, reversed names and status', () => { expect(searchCadets([cadet], 'jordan')).toHaveLength(1); expect(searchCadets([cadet], 'rivera')).toHaveLength(1); expect(searchCadets([cadet], 'Rivera, Jordan')).toHaveLength(1); expect(searchCadets([{ ...cadet, status: 'INACTIVE' }], '', 'ACTIVE')).toHaveLength(0); expect(searchCadets([{ ...cadet, status: 'INACTIVE' }], '', 'INACTIVE')).toHaveLength(1) })
  it('recommends gender-aware defaults without restricting manual selection', () => { expect(bundleSuggestions('Male')).toEqual(['Male NSU','Male SDB','PT','Drill','BLT']); expect(bundleSuggestions('Female')).toContain('Female SDB') })
  it('derives availability and readiness without auto-fulfillment', () => { expect(requirementAvailability(need, [{ entityId: 'shoe', name: 'Shoe', onHand: 3, version: 0, appliedEventIds: [] }])).toMatchObject({ available: true, onHand: 3 }); expect(need.status).toBe('OPEN'); expect(cadetReadiness([need])).toMatchObject({ status: 'INCOMPLETE', percent: 0 }); expect(cadetReadiness([])).toMatchObject({ status: 'READY', percent: 100 }); expect(cadetReadiness([{ ...need, quantityFulfilled: 2, status: 'FULFILLED' }])).toMatchObject({ status: 'READY', percent: 100 }) })
  it('validates requirement quantities and lifecycle', () => { expect(() => validateRequirement(need)).not.toThrow(); expect(() => validateRequirement({ ...need, quantityNeeded: 0 })).toThrow(/quantities/); expect(() => validateRequirement({ ...need, quantityFulfilled: 3 })).toThrow(/quantities/) })
})

describe('Stage 3A factory bundles', () => {
  it('contains the seven exact, unique presets', () => { expect(FACTORY_BUNDLES.map(b => b.displayName)).toEqual(['Male NSU','Female NSU','Male SDB','Female SDB','PT','Drill','BLT']); expect(new Set(FACTORY_BUNDLES.map(b => b.bundleId)).size).toBe(7) })
  it('preserves exact Male NSU and SDB rules', () => { expect(FACTORY_BUNDLES[0].lines.map(l => l.displayLabel)).toEqual(['Male Khaki Shirt','Black Trousers','Garrison Cap','Black Belt','Buckle','White Dress Shirt','Black Socks','Black Oxfords']); const sdb = FACTORY_BUNDLES.find(b => b.displayName === 'Male SDB')!; expect(sdb.lines.map(l => [l.displayLabel,l.required])).toEqual([['Male SDB Jacket',true],['Necktie',true],['White Dress Shirt',false]]); expect(JSON.stringify(sdb)).not.toMatch(/combo cover|white gloves|undershirt/i) })
  it('contains exact remaining lines', () => { const lines = (name: string) => FACTORY_BUNDLES.find(b => b.displayName === name)!.lines.map(l => l.displayLabel); expect(lines('Female NSU')).toEqual(['Khaki Overblouse','Black Slacks','Garrison Cap','Black Oxfords','Pumps']); expect(lines('Female SDB')).toEqual(['Female SDB Jacket','Neck Tabs','White Dress Shirt']); expect(lines('PT')).toEqual(['Gold PT Shirt','PT Shorts','Khaki Ball Cap']); expect(lines('Drill')).toEqual(['Tracksuit Top','Tracksuit Bottom']); expect(lines('BLT')).toEqual(['Khaki Shirt','Khaki Trousers','Khaki Belt','Brass Buckle','Platoon Shirt']) })
  it('rejects blank, duplicate and nonpositive bundle definitions', () => { const valid = FACTORY_BUNDLES[0]; expect(() => validateBundle(valid)).not.toThrow(); expect(() => validateBundle({ ...valid, displayName: '' })).toThrow(/name/); expect(() => validateBundle({ ...valid, lines: [valid.lines[0], valid.lines[0]] })).toThrow(/IDs/); expect(() => validateBundle({ ...valid, lines: [{ ...valid.lines[0], defaultQuantity: 0 }] })).toThrow(/quantity/) })
})
