import { describe, expect, it } from 'vitest'
import { AuthorizationService, ROLE_PERMISSIONS, issueCredential } from '../auth/authorization'
import { MockIdentityProvider } from '../identity/identity'
import { MemoryRepository } from '../storage/repository'
import { MockSyncProvider } from '../sync/mock'
import { ArgusReplica } from '../distributed/replica'
import { FACTORY_BUNDLES } from './domain'

async function setup(role: 'SUPPLY_OFFICER'|'SUPPLY_ASSISTANT' = 'SUPPLY_OFFICER', provider = new MockSyncProvider(), name = 'user') { const root = new MockIdentityProvider('root'), user = new MockIdentityProvider(name), auth = new AuthorizationService('mock:root', user); await auth.acceptCredential(await issueCredential(root, { subjectPublicIdentity: await user.getPublicIdentity(), role, permissions: [...ROLE_PERMISSIONS[role]], issuedAt: '2020-01-01T00:00:00Z' })); const replica = new ArgusReplica(new MemoryRepository(), user, auth, provider); await replica.initialize([{ entityId: 'shoe', name: 'Black Oxfords', onHand: 3, version: 0 }]); return replica }
describe('Stage 3A signed projections', () => {
  it('seeds factory bundles exactly once', async () => { const r = await setup(); await r.initialize(); expect((await r.snapshot()).bundles).toHaveLength(7) })
  it('creates, updates and deactivates cadets without deleting records', async () => { const r = await setup(); r.online = false; const created = await r.createCadet({ fullName: 'Casey Bennett', gender: 'Male', nsLevel: 'NS1', status: 'ACTIVE' }, { eventId: 'create' }); expect(created.entityId).toMatch(/^cadet_/); await r.updateCadet(created.entityId, { nsLevel: 'NS2', status: 'INACTIVE' }, { eventId: 'update' }); expect((await r.snapshot()).cadets[0]).toMatchObject({ nsLevel: 'NS2', status: 'INACTIVE', version: 2 }); expect((await r.snapshot()).events).toHaveLength(2) })
  it('rejects unauthorized cadet and bundle mutation at domain API', async () => { const r = await setup('SUPPLY_ASSISTANT'); await expect(r.createCadet({ fullName: 'Alex Morgan', gender: 'Male', nsLevel: 'NS1', status: 'ACTIVE' })).rejects.toThrow(/cadets.manage/); await expect(r.updateBundle('bundle-male-nsu', { ...FACTORY_BUNDLES[0], displayName: 'Changed', active: true, purpose: 'NSU', lines: FACTORY_BUNDLES[0].lines })).rejects.toThrow(/bundles.manage/) })
  it('preserves immutable bundle versions', async () => { const r = await setup(); r.online = false; const original = structuredClone((await r.snapshot()).bundles[0].versions[0]); await r.updateBundle(original.bundleId, { displayName: original.displayName, genderApplicability: original.genderApplicability, purpose: original.purpose, lines: [...original.lines, { lineId: 'new', displayLabel: 'Mapped later', required: false, supportsSizing: true, defaultQuantity: 1, order: 9 }], active: true }, { eventId: 'bundle-update' }); const bundle = (await r.snapshot()).bundles[0]; expect(bundle.currentVersion).toBe(2); expect(bundle.versions).toHaveLength(2); expect(bundle.versions[0]).toEqual(original) })
  it('adds, partially fulfills and cancels Still Needed with history retained', async () => { const r = await setup(); r.online = false; const cadet = await r.createCadet({ fullName: 'Taylor Brooks', gender: 'Female', nsLevel: 'NS3', status: 'ACTIVE' }); const event = await r.addStillNeeded({ cadetId: cadet.entityId, itemId: 'shoe', displayLabel: 'Black Oxfords', size: '10', quantityNeeded: 2, quantityFulfilled: 0, status: 'OPEN', firstNeededAt: '2026-01-01T00:00:00Z', source: 'MANUAL' }); await r.updateStillNeeded(event.entityId, { quantityFulfilled: 1, status: 'PARTIALLY_FULFILLED' }); await r.updateStillNeeded(event.entityId, { status: 'CANCELLED' }); const state = await r.snapshot(); expect(state.stillNeeded[0]).toMatchObject({ status: 'CANCELLED', quantityFulfilled: 1, version: 3 }); expect(state.events.filter(e => e.event.entityId === event.entityId)).toHaveLength(3) })
  it('synchronizes, deduplicates, and detects concurrent cadet and bundle edits', async () => { const provider = new MockSyncProvider(), root = new MockIdentityProvider('shared-root'), identities = [new MockIdentityProvider('a'), new MockIdentityProvider('b')], auth = new AuthorizationService('mock:shared-root', identities[0]); for (const user of identities) await auth.acceptCredential(await issueCredential(root, { subjectPublicIdentity: await user.getPublicIdentity(), role: 'SUPPLY_OFFICER', permissions: [...ROLE_PERMISSIONS.SUPPLY_OFFICER], issuedAt: '2020-01-01T00:00:00Z' })); const a = new ArgusReplica(new MemoryRepository(), identities[0], auth, provider), b = new ArgusReplica(new MemoryRepository(), identities[1], auth, provider); await a.initialize([{ entityId: 'shoe', name: 'Black Oxfords', onHand: 3, version: 0 }]); await b.initialize([{ entityId: 'shoe', name: 'Black Oxfords', onHand: 3, version: 0 }]); a.online = false; const create = await a.createCadet({ fullName: 'Jordan Rivera', gender: 'Male', nsLevel: 'NS1', status: 'ACTIVE' }, { eventId: 'cadet-create' }); a.online = true; await a.sync(); await b.sync(); await b.receive(create); expect((await b.snapshot()).cadets).toHaveLength(1); a.online = b.online = false; await a.updateCadet(create.entityId, { nsLevel: 'NS2' }, { eventId: 'cadet-a' }); await b.updateCadet(create.entityId, { nsLevel: 'NS3' }, { eventId: 'cadet-b' }); const base = FACTORY_BUNDLES[0]; await a.updateBundle(base.bundleId, { displayName: base.displayName, genderApplicability: base.genderApplicability, purpose: base.purpose, lines: [...base.lines, { ...base.lines[0], lineId: 'x', displayLabel: 'X' }], active: true }, { eventId: 'bundle-a' }); await b.updateBundle(base.bundleId, { displayName: base.displayName, genderApplicability: base.genderApplicability, purpose: base.purpose, lines: base.lines.slice(1), active: true }, { eventId: 'bundle-b' }); a.online = b.online = true; await a.sync(); await b.sync(); await a.sync(); expect((await a.snapshot()).conflicts.some(c => c.entityId === create.entityId)).toBe(true); expect((await a.snapshot()).conflicts.some(c => c.entityId === base.bundleId)).toBe(true) })
})
