import { describe, expect, it } from 'vitest'
import { AuthorizationService, ROLE_PERMISSIONS, issueCredential } from '../auth/authorization'
import { ArgusReplica } from '../distributed/replica'
import { MockIdentityProvider } from '../identity/identity'
import { MemoryRepository } from '../storage/repository'
import { MockSyncProvider } from '../sync/mock'

async function setup(role: 'SUPPLY_OFFICER'|'SUPPLY_ASSISTANT' = 'SUPPLY_OFFICER', provider = new MockSyncProvider(), identityName = 'operator') {
  const root = new MockIdentityProvider('root-3b'), identity = new MockIdentityProvider(identityName), authorization = new AuthorizationService('mock:root-3b', identity)
  await authorization.acceptCredential(await issueCredential(root, { subjectPublicIdentity: await identity.getPublicIdentity(), role, permissions: [...ROLE_PERMISSIONS[role]], issuedAt: '2020-01-01T00:00:00Z' }))
  const repository = new MemoryRepository(), replica = new ArgusReplica(repository, identity, authorization, provider)
  await replica.initialize([{ entityId:'shirt-m',name:'PT Shirt Medium',onHand:3,issued:0,version:0 },{ entityId:'belt',name:'Black Belt',onHand:4,issued:0,version:0 },{ entityId:'jacket',name:'SDB Jacket Medium',onHand:1,issued:0,version:0 }])
  replica.online=false; if(role==='SUPPLY_ASSISTANT'){const id=`cadet-${identityName}`;await repository.transaction(s=>s.cadets.push({cadetId:id,fullName:'Jordan Rivera',gender:'Male',nsLevel:'NS2',status:'ACTIVE',sizes:{},currentProperty:[],createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',version:1,appliedEventIds:[]}));return {replica,cadet:{entityId:id}}} const cadet = await replica.createCadet({ fullName:'Jordan Rivera',gender:'Male',nsLevel:'NS2',status:'ACTIVE',sizes:{'PT Shirt':'Medium'} },{eventId:`cadet-${identityName}`}); return { replica,cadet }
}
async function pair(){const provider=new MockSyncProvider(),root=new MockIdentityProvider('pair-root'),ids=[new MockIdentityProvider('pair-a'),new MockIdentityProvider('pair-b')],auth=new AuthorizationService('mock:pair-root',ids[0]);for(const id of ids)await auth.acceptCredential(await issueCredential(root,{subjectPublicIdentity:await id.getPublicIdentity(),role:'SUPPLY_OFFICER',permissions:[...ROLE_PERMISSIONS.SUPPLY_OFFICER],issuedAt:'2020-01-01T00:00:00Z'}));const replicas=ids.map(id=>new ArgusReplica(new MemoryRepository(),id,auth,provider));for(const r of replicas)await r.initialize([{ entityId:'shirt-m',name:'PT Shirt Medium',onHand:3,issued:0,version:0 },{ entityId:'belt',name:'Black Belt',onHand:4,issued:0,version:0 },{ entityId:'jacket',name:'SDB Jacket Medium',onHand:1,issued:0,version:0 }]);replicas[0].online=false;const cadet=await replicas[0].createCadet({fullName:'Jordan Rivera',gender:'Male',nsLevel:'NS2',status:'ACTIVE'},{eventId:'shared-cadet'});replicas[0].online=true;await replicas[0].sync();await replicas[1].sync();replicas[0].online=replicas[1].online=false;return{provider,a:replicas[0],b:replicas[1],cadet}}

describe('Stage 3B issue and return transactions',()=>{
  it('atomically issues sized and unsized multiple lines with stable grouping and history',async()=>{const {replica,cadet}=await setup(); const event=await replica.issueTransaction({transactionId:'tx-issue',cadetId:cadet.entityId,lines:[{lineId:'shirt',itemId:'shirt-m',label:'PT Shirt',size:'Medium',quantity:2},{lineId:'belt',itemId:'belt',label:'Black Belt',quantity:1}]},{eventId:'issue-event'}); const state=await replica.snapshot(); expect(event.payload.transactionId).toBe('tx-issue'); expect(state.inventory.map(i=>i.onHand)).toEqual([1,3,1]); expect(state.cadets[0].currentProperty).toHaveLength(2); expect(state.transactions[0]).toMatchObject({transactionId:'tx-issue',eventId:'issue-event',transactionType:'ISSUE'}); expect(state.events).toHaveLength(2); expect(state.outbox).toHaveLength(2)})
  it('creates merged Still Needed only for required missing lines and preserves bundle version snapshot',async()=>{const {replica,cadet}=await setup(); const input={transactionId:'partial-1',cadetId:cadet.entityId,lines:[{lineId:'belt',itemId:'belt',label:'Black Belt',quantity:1}],missingLines:[{lineId:'missing',itemId:'jacket',label:'SDB Jacket',size:'Medium',quantity:1,required:true as const}],bundleId:'bundle-male-sdb',bundleVersion:1};await replica.issueTransaction(input,{eventId:'partial-event-1'});await replica.issueTransaction({...input,transactionId:'partial-2',lines:[]},{eventId:'partial-event-2'});const state=await replica.snapshot();expect(state.stillNeeded).toHaveLength(1);expect(state.stillNeeded[0]).toMatchObject({quantityNeeded:2,source:'INCOMPLETE_ISSUE',bundleVersion:1});expect(state.transactions[0].bundleSnapshot?.version).toBe(1)})
  it('fulfills exact-size requirements partially then fully but not with a wrong size',async()=>{const {replica,cadet}=await setup();await replica.addStillNeeded({cadetId:cadet.entityId,itemId:'shirt-m',displayLabel:'PT Shirt',size:'Medium',quantityNeeded:2,quantityFulfilled:0,status:'OPEN',firstNeededAt:'2026-01-01T00:00:00Z',source:'MANUAL',requirementId:'need-shirt'});await replica.issueTransaction({transactionId:'wrong',cadetId:cadet.entityId,lines:[{lineId:'w',itemId:'shirt-m',label:'PT Shirt',size:'Large',quantity:1}]},{eventId:'wrong-event'});expect((await replica.snapshot()).stillNeeded[0].status).toBe('OPEN');await replica.issueTransaction({transactionId:'right',cadetId:cadet.entityId,lines:[{lineId:'r',itemId:'shirt-m',label:'PT Shirt',size:'Medium',quantity:2,requirementId:'need-shirt'}]},{eventId:'right-event'});expect((await replica.snapshot()).stillNeeded[0]).toMatchObject({status:'FULFILLED',quantityFulfilled:2})})
  it('rejects invalid quantities, stale stock, inactive cadets, and duplicate confirmation is idempotent',async()=>{const {replica,cadet}=await setup();await expect(replica.issueTransaction({transactionId:'zero',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'belt',label:'Belt',quantity:0}]})).rejects.toThrow(/quantities/);await expect(replica.issueTransaction({transactionId:'too-many',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'jacket',label:'Jacket',quantity:2}]})).rejects.toThrow(/Stock changed/);const args={transactionId:'once',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'belt',label:'Belt',quantity:1}]};await replica.issueTransaction(args,{eventId:'same'});await replica.issueTransaction(args,{eventId:'same'});expect((await replica.snapshot()).inventory.find(i=>i.entityId==='belt')?.onHand).toBe(3);await replica.updateCadet(cadet.entityId,{status:'INACTIVE'});await expect(replica.issueTransaction({transactionId:'inactive',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'belt',label:'Belt',quantity:1}]})).rejects.toThrow(/Inactive/)})
  it('supports partial and full multi-item return without creating requirements or deleting issue history',async()=>{const {replica,cadet}=await setup();await replica.issueTransaction({transactionId:'issue',cadetId:cadet.entityId,lines:[{lineId:'s',itemId:'shirt-m',label:'PT Shirt',size:'Medium',quantity:3},{lineId:'b',itemId:'belt',label:'Belt',quantity:1}]},{eventId:'issue'});let state=await replica.snapshot();const [shirt,belt]=state.cadets[0].currentProperty;await replica.returnTransaction({transactionId:'return',cadetId:cadet.entityId,lines:[{lineId:'s',propertyId:shirt.propertyId,quantity:2},{lineId:'b',propertyId:belt.propertyId,quantity:1}]},{eventId:'return'});state=await replica.snapshot();expect(state.cadets[0].currentProperty).toHaveLength(1);expect(state.cadets[0].currentProperty[0].quantity).toBe(1);expect(state.inventory.find(i=>i.entityId==='shirt-m')?.onHand).toBe(2);expect(state.stillNeeded).toHaveLength(0);expect(state.events.map(e=>e.event.eventType)).toContain('ITEM_ISSUED');expect(state.transactions.at(-1)?.transactionType).toBe('RETURN')})
  it('rejects excessive, zero, and not-owned returns',async()=>{const {replica,cadet}=await setup();await expect(replica.returnTransaction({transactionId:'none',cadetId:cadet.entityId,lines:[{lineId:'x',propertyId:'none',quantity:1}]})).rejects.toThrow(/no longer has/);await replica.issueTransaction({transactionId:'i',cadetId:cadet.entityId,lines:[{lineId:'b',itemId:'belt',label:'Belt',quantity:1}]});const property=(await replica.snapshot()).cadets[0].currentProperty[0];await expect(replica.returnTransaction({transactionId:'bad',cadetId:cadet.entityId,lines:[{lineId:'x',propertyId:property.propertyId,quantity:0}]})).rejects.toThrow(/exceeds/);await expect(replica.returnTransaction({transactionId:'bad2',cadetId:cadet.entityId,lines:[{lineId:'x',propertyId:property.propertyId,quantity:2}]})).rejects.toThrow(/exceeds/)})
  it('persists offline outbox and converges without duplicate delivery',async()=>{const {a,b,cadet}=await pair();await a.issueTransaction({transactionId:'offline',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'belt',label:'Belt',quantity:1}]},{eventId:'offline-event'});expect((await a.snapshot()).outbox.some(o=>o.eventId==='offline-event')).toBe(true);a.online=true;await a.sync();b.online=true;await b.sync();await b.sync();expect((await b.snapshot()).inventory.find(i=>i.entityId==='belt')?.onHand).toBe(3)})
  it('detects competing final-unit issues and never makes inventory negative',async()=>{const {a,b,cadet}=await pair();await a.issueTransaction({transactionId:'a',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'jacket',label:'Jacket',quantity:1}]},{eventId:'a-event'});await b.issueTransaction({transactionId:'b',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'jacket',label:'Jacket',quantity:1}]},{eventId:'b-event'});a.online=b.online=true;await a.sync();await b.sync();await a.sync();const state=await a.snapshot();expect(state.inventory.find(i=>i.entityId==='jacket')?.onHand).toBe(0);expect(state.conflicts.some(c=>c.status==='OPEN')).toBe(true);expect(state.events.some(e=>e.event.eventId==='b-event')).toBe(true)})
  it('enforces issue, return, and correction permissions in domain APIs',async()=>{const {replica,cadet}=await setup('SUPPLY_ASSISTANT');await replica.issueTransaction({transactionId:'allowed',cadetId:cadet.entityId,lines:[{lineId:'x',itemId:'belt',label:'Belt',quantity:1}]});const property=(await replica.snapshot()).cadets[0].currentProperty[0];await replica.returnTransaction({transactionId:'return-allowed',cadetId:cadet.entityId,lines:[{lineId:'x',propertyId:property.propertyId,quantity:1}]});await expect(replica.correct('event','belt','size','Medium','Correction')).rejects.toThrow(/inventory.adjust/)})
})
