import { IDBFactory } from 'fake-indexeddb'
import { describe, expect, it } from 'vitest'
import { AuthorizationService, ROLE_PERMISSIONS, issueCredential } from '../auth/authorization'
import { ArgusReplica } from '../distributed/replica'
import { MockIdentityProvider } from '../identity/identity'
import { IndexedDbRepository, MemoryRepository, type ArgusRepository } from '../storage/repository'
import { MockSyncProvider } from '../sync/mock'

const inventory = [
  {entityId:'shirt-m',name:'PT Shirt',category:'PT',variant:'Medium',niin:'M-1',onHand:3,issued:0,countIncrement:1,active:true,version:0},
  {entityId:'shirt-l',name:'PT Shirt',category:'PT',variant:'Large',niin:'L-1',onHand:2,issued:0,countIncrement:1,active:true,version:0},
  {entityId:'belt',name:'Black Belt',category:'NSU',variant:'No variant',niin:'B-1',onHand:4,issued:0,countIncrement:1,active:true,version:0},
  {entityId:'jacket-m',name:'SDB Jacket',category:'SDB',variant:'Medium',niin:'J-1',onHand:1,issued:0,countIncrement:1,active:true,version:0},
]
async function setup(role:'SUPPLY_OFFICER'|'SUPPLY_ASSISTANT'='SUPPLY_OFFICER',repository:ArgusRepository=new MemoryRepository(),provider=new MockSyncProvider(),name='user'){
 const root=new MockIdentityProvider('root'),identity=new MockIdentityProvider(name),auth=new AuthorizationService('mock:root',identity);await auth.acceptCredential(await issueCredential(root,{subjectPublicIdentity:await identity.getPublicIdentity(),role,permissions:[...ROLE_PERMISSIONS[role]],issuedAt:'2020-01-01T00:00:00Z'}));const replica=new ArgusReplica(repository,identity,auth,provider);await replica.initialize(inventory);replica.online=false
 let cadetId=`cadet-${name}`;if(role==='SUPPLY_OFFICER'){cadetId=(await replica.createCadet({fullName:'Jordan Rivera',gender:'Male',nsLevel:'NS2',status:'ACTIVE',sizes:{'PT Shirt':'Large'}},{eventId:`cadet-event-${name}`})).entityId}else await repository.transaction(state=>state.cadets.push({cadetId,fullName:'Jordan Rivera',gender:'Male',nsLevel:'NS2',status:'ACTIVE',sizes:{},currentProperty:[],createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',version:1,appliedEventIds:[]}))
 return{replica,repository,cadetId,identity,auth}
}
async function pair(){const provider=new MockSyncProvider(),root=new MockIdentityProvider('pair-root'),ids=[new MockIdentityProvider('a'),new MockIdentityProvider('b')],auth=new AuthorizationService('mock:pair-root',ids[0]);for(const identity of ids)await auth.acceptCredential(await issueCredential(root,{subjectPublicIdentity:await identity.getPublicIdentity(),role:'SUPPLY_OFFICER',permissions:[...ROLE_PERMISSIONS.SUPPLY_OFFICER],issuedAt:'2020-01-01T00:00:00Z'}));const replicas=ids.map(identity=>new ArgusReplica(new MemoryRepository(),identity,auth,provider));for(const replica of replicas)await replica.initialize(inventory);replicas[0].online=false;const cadetId=(await replicas[0].createCadet({fullName:'Casey Bennett',gender:'Female',nsLevel:'NS3',status:'ACTIVE'},{eventId:'shared-cadet'})).entityId;replicas[0].online=true;await replicas[0].sync();await replicas[1].sync();replicas[0].online=replicas[1].online=false;return{a:replicas[0],b:replicas[1],cadetId}}

describe('Stage 3B authoritative transactions',()=>{
 it('issues multiple sized and unsized SKUs atomically with provenance',async()=>{const{replica,cadetId}=await setup();await replica.issueTransaction({transactionId:'issue-1',cadetId,lines:[{lineId:'large',itemId:'shirt-l',quantity:2},{lineId:'belt',itemId:'belt',quantity:1}]},{eventId:'issue-event'});const state=await replica.snapshot();expect(state.inventory.find(i=>i.entityId==='shirt-l')?.onHand).toBe(0);expect(state.inventory.find(i=>i.entityId==='shirt-m')?.onHand).toBe(3);expect(state.cadets[0].currentProperty).toEqual(expect.arrayContaining([expect.objectContaining({itemId:'shirt-l',variant:'Large',issueTransactionId:'issue-1'}),expect.objectContaining({itemId:'belt',variant:'No variant'})]));expect(state.transactions[0]).toMatchObject({transactionId:'issue-1',eventId:'issue-event',transactionType:'ISSUE'})})
 it('derives label and variant from SKU and rejects duplicate SKU lines',async()=>{const{replica,cadetId}=await setup();await replica.issueTransaction({transactionId:'canonical',cadetId,lines:[{lineId:'x',itemId:'shirt-m',quantity:1}]});expect((await replica.snapshot()).transactions[0].lines[0]).toMatchObject({label:'PT Shirt',variant:'Medium'});await expect(replica.issueTransaction({transactionId:'duplicate',cadetId,lines:[{lineId:'a',itemId:'belt',quantity:1},{lineId:'b',itemId:'belt',quantity:1}]})).rejects.toThrow(/Duplicate inventory/)})
 it('validates every line before mutation and rolls back malformed second line',async()=>{const{replica,cadetId}=await setup();await expect(replica.issueTransaction({transactionId:'rollback',cadetId,lines:[{lineId:'good',itemId:'belt',quantity:1},{lineId:'bad',itemId:'missing',quantity:1}]})).rejects.toThrow(/not found/);const state=await replica.snapshot();expect(state.inventory.find(i=>i.entityId==='belt')?.onHand).toBe(4);expect(state.cadets[0].currentProperty).toHaveLength(0);expect(state.transactions).toHaveLength(0)})
 it('creates mapped and unmapped required needs, merges provenance, and ignores optional omissions',async()=>{const{replica,cadetId}=await setup();const partial=(id:string)=>replica.issueTransaction({transactionId:id,cadetId,lines:[{lineId:'belt',itemId:'belt',quantity:1}],missingLines:[{lineId:`required-${id}`,itemId:'jacket-m',label:'SDB Jacket',variant:'Medium',quantity:1,required:true},{lineId:`unmapped-${id}`,label:'Rank Device',quantity:1,required:true}]},{eventId:`event-${id}`});await partial('partial-1');await partial('partial-2');const needs=(await replica.snapshot()).stillNeeded;expect(needs).toHaveLength(2);expect(needs.find(n=>n.itemId==='jacket-m')).toMatchObject({quantityNeeded:2,relatedTransactionIds:['partial-1','partial-2']});expect(needs.find(n=>!n.itemId)?.displayLabel).toBe('Rank Device')})
 it('resolves the declared current bundle version rather than array order and preserves its snapshot',async()=>{const{replica,repository,cadetId}=await setup();const base=(await replica.snapshot()).bundles[0].versions[0],v1={...base,bundleId:'ordered',version:1,eventId:'v1',lines:[{lineId:'old',itemId:'shirt-m',displayLabel:'PT Shirt',required:true,supportsSizing:true,defaultQuantity:1,order:0}]},v2={...base,bundleId:'ordered',version:2,eventId:'v2',priorVersion:1,lines:[{lineId:'new',itemId:'shirt-l',displayLabel:'PT Shirt',required:true,supportsSizing:true,defaultQuantity:1,order:0}]};await repository.transaction(state=>state.bundles.push({bundleId:'ordered',currentVersion:2,versions:[v2,v1],appliedEventIds:['v1','v2']}));await replica.issueTransaction({transactionId:'bundle-issue',cadetId,bundleId:'ordered',bundleVersion:2,lines:[{lineId:'new',itemId:'shirt-l',quantity:1}]},{eventId:'bundle-event'});expect((await replica.snapshot()).transactions[0]).toMatchObject({bundleId:'ordered',bundleVersion:2,bundleSnapshot:{version:2,eventId:'v2'}})})
 it('fulfills only exact SKU and variant, including partial fulfillment',async()=>{const{replica,cadetId}=await setup();await replica.addStillNeeded({requirementId:'need-m',cadetId,itemId:'shirt-m',displayLabel:'PT Shirt',size:'Medium',quantityNeeded:2,quantityFulfilled:0,status:'OPEN',firstNeededAt:'2026-01-01T00:00:00Z',source:'MANUAL'});await replica.issueTransaction({transactionId:'wrong',cadetId,lines:[{lineId:'l',itemId:'shirt-l',quantity:1}]});expect((await replica.snapshot()).stillNeeded[0].status).toBe('OPEN');await replica.issueTransaction({transactionId:'partial',cadetId,lines:[{lineId:'m',itemId:'shirt-m',quantity:1,requirementId:'need-m'}]});expect((await replica.snapshot()).stillNeeded[0]).toMatchObject({status:'PARTIALLY_FULFILLED',quantityFulfilled:1});await replica.issueTransaction({transactionId:'full',cadetId,lines:[{lineId:'m2',itemId:'shirt-m',quantity:1,requirementId:'need-m'}]});expect((await replica.snapshot()).stillNeeded[0].status).toBe('FULFILLED')})
 it('supports multi-line partial return and permits returns for inactive cadets',async()=>{const{replica,cadetId}=await setup();await replica.issueTransaction({transactionId:'issued',cadetId,lines:[{lineId:'shirt',itemId:'shirt-m',quantity:2},{lineId:'belt',itemId:'belt',quantity:1}]});await replica.updateCadet(cadetId,{status:'INACTIVE'});const properties=(await replica.snapshot()).cadets[0].currentProperty;await replica.returnTransaction({transactionId:'returned',cadetId,lines:[{lineId:'shirt-return',propertyId:properties[0].propertyId,quantity:1},{lineId:'belt-return',propertyId:properties[1].propertyId,quantity:1}]},{eventId:'return-event'});const state=await replica.snapshot();expect(state.cadets[0].currentProperty).toEqual([expect.objectContaining({itemId:'shirt-m',quantity:1})]);expect(state.inventory.find(i=>i.entityId==='belt')?.onHand).toBe(4);expect(state.stillNeeded).toHaveLength(0);await expect(replica.issueTransaction({transactionId:'inactive-issue',cadetId,lines:[{lineId:'x',itemId:'belt',quantity:1}]})).rejects.toThrow(/Inactive/)})
 it('rejects invalid and excessive return quantities',async()=>{const{replica,cadetId}=await setup();await replica.issueTransaction({transactionId:'i',cadetId,lines:[{lineId:'x',itemId:'belt',quantity:1}]});const id=(await replica.snapshot()).cadets[0].currentProperty[0].propertyId;for(const quantity of [0,-1,2])await expect(replica.returnTransaction({transactionId:`r-${quantity}`,cadetId,lines:[{lineId:'x',propertyId:id,quantity}]})).rejects.toThrow();await expect(replica.returnTransaction({transactionId:'none',cadetId,lines:[{lineId:'x',propertyId:'missing',quantity:1}]})).rejects.toThrow(/no longer/)})
 it('makes duplicate retries idempotent and rejects event and transaction collisions',async()=>{const{replica,cadetId}=await setup();const input={transactionId:'stable',cadetId,lines:[{lineId:'x',itemId:'belt',quantity:1}]};await replica.issueTransaction(input,{eventId:'stable-event'});await replica.issueTransaction(input,{eventId:'stable-event'});expect((await replica.snapshot()).inventory.find(i=>i.entityId==='belt')?.onHand).toBe(3);await expect(replica.issueTransaction({...input,transactionId:'other'},{eventId:'stable-event'})).rejects.toThrow(/Event ID collision/);await expect(replica.issueTransaction({...input,lines:[{lineId:'x',itemId:'shirt-m',quantity:1}]},{eventId:'different-event'})).rejects.toThrow(/Transaction ID collision/)})
 it('quarantines an entire conflicting transaction against the inventory SKU with both events',async()=>{const{a,b,cadetId}=await pair();await a.issueTransaction({transactionId:'a-tx',cadetId,lines:[{lineId:'j',itemId:'jacket-m',quantity:1},{lineId:'belt',itemId:'belt',quantity:1}]},{eventId:'a-event'});await b.issueTransaction({transactionId:'b-tx',cadetId,lines:[{lineId:'j',itemId:'jacket-m',quantity:1},{lineId:'shirt',itemId:'shirt-m',quantity:1}]},{eventId:'b-event'});a.online=b.online=true;await a.sync();await b.sync();await a.sync();const state=await a.snapshot(),conflict=state.conflicts.find(c=>c.entityId==='jacket-m');expect(conflict?.eventIds.sort()).toEqual(['a-event','b-event']);expect(conflict).toMatchObject({status:'OPEN',inventoryItemIds:['jacket-m'],cadetId});expect(state.inventory.find(i=>i.entityId==='jacket-m')?.onHand).toBe(0);expect(state.inventory.find(i=>i.entityId==='shirt-m')?.onHand).toBe(3);expect(state.events.filter(e=>['a-event','b-event'].includes(e.event.eventId))).toHaveLength(2)})
 it('atomically accepts only one simultaneous issue against the final unit',async()=>{const{replica,cadetId}=await setup();await Promise.all([replica.issueTransaction({transactionId:'race-a',cadetId,lines:[{lineId:'j',itemId:'jacket-m',quantity:1}]},{eventId:'race-event-a'}),replica.issueTransaction({transactionId:'race-b',cadetId,lines:[{lineId:'j',itemId:'jacket-m',quantity:1}]},{eventId:'race-event-b'})]);const state=await replica.snapshot();expect(state.inventory.find(i=>i.entityId==='jacket-m')?.onHand).toBe(0);expect(state.transactions.filter(t=>t.lines.some(line=>line.itemId==='jacket-m'))).toHaveLength(1);expect(state.events.filter(e=>e.event.eventId.startsWith('race-event'))).toHaveLength(2);expect(state.conflicts.some(c=>c.eventIds.includes('race-event-a')&&c.eventIds.includes('race-event-b'))).toBe(true)})
 it('accepts only one simultaneous return of the same property',async()=>{const{replica,cadetId}=await setup();await replica.issueTransaction({transactionId:'return-source',cadetId,lines:[{lineId:'belt',itemId:'belt',quantity:1}]},{eventId:'return-source-event'});const propertyId=(await replica.snapshot()).cadets[0].currentProperty[0].propertyId;await Promise.all([replica.returnTransaction({transactionId:'return-race-a',cadetId,lines:[{lineId:'belt',propertyId,quantity:1}]},{eventId:'return-race-event-a'}),replica.returnTransaction({transactionId:'return-race-b',cadetId,lines:[{lineId:'belt',propertyId,quantity:1}]},{eventId:'return-race-event-b'})]);const state=await replica.snapshot();expect(state.inventory.find(i=>i.entityId==='belt')?.onHand).toBe(4);expect(state.cadets[0].currentProperty).toHaveLength(0);expect(state.transactions.filter(t=>t.transactionType==='RETURN')).toHaveLength(1);expect(state.events.filter(e=>e.event.eventId.startsWith('return-race-event'))).toHaveLength(2);expect(state.conflicts.some(c=>c.reason.includes('return'))).toBe(true)})
 it('enforces assistant correction denial while allowing issue and return',async()=>{const{replica,cadetId}=await setup('SUPPLY_ASSISTANT');await replica.issueTransaction({transactionId:'i',cadetId,lines:[{lineId:'x',itemId:'belt',quantity:1}]});const property=(await replica.snapshot()).cadets[0].currentProperty[0];await replica.returnTransaction({transactionId:'r',cadetId,lines:[{lineId:'x',propertyId:property.propertyId,quantity:1}]});await expect(replica.correct('i','belt','variant','Other','reason')).rejects.toThrow(/inventory.adjust/)})
 it('persists offline issue and return transactions through IndexedDB reopen',async()=>{const factory=new IDBFactory();Object.defineProperty(globalThis,'indexedDB',{configurable:true,value:factory});const first=new IndexedDbRepository('stage3b-durable'),setupResult=await setup('SUPPLY_OFFICER',first);await setupResult.replica.issueTransaction({transactionId:'offline-issue',cadetId:setupResult.cadetId,lines:[{lineId:'x',itemId:'belt',quantity:1}]},{eventId:'offline-issue-event'});const property=(await first.snapshot()).cadets[0].currentProperty[0];await setupResult.replica.returnTransaction({transactionId:'offline-return',cadetId:setupResult.cadetId,lines:[{lineId:'x',propertyId:property.propertyId,quantity:1}]},{eventId:'offline-return-event'});first.close();const reopened=new IndexedDbRepository('stage3b-durable');await reopened.initialize();const state=await reopened.snapshot();expect(state.transactions.map(t=>t.transactionId)).toEqual(['offline-issue','offline-return']);expect(state.outbox.map(o=>o.eventId)).toEqual(expect.arrayContaining(['offline-issue-event','offline-return-event']));expect(state.cadets[0].currentProperty).toHaveLength(0);reopened.close()})
})
