import type { AuthorizationService } from '../auth/authorization'
import { canonicalize } from './canonical'
import type { ArgusIdentityProvider } from '../identity/identity'
import type { ArgusPermission, ConflictRecord, InventoryProjection, MissingIssueLine, SignedArgusEvent, SupplyTransactionLine, UnsignedArgusEvent } from './types'
import type { ArgusRepository, RepositoryState } from '../storage/repository'
import type { MockSyncProvider } from '../sync/mock'
import type { BundleVersionProjection, CadetProjection, StillNeededProjection } from './types'
import { FACTORY_BUNDLES, validateBundle, validateCadet, validateRequirement } from '../stage3/domain'

const permissionFor = (type: SignedArgusEvent['eventType']): ArgusPermission | undefined => ({ INVENTORY_ITEM_CREATED: 'inventory.create', INVENTORY_ITEM_UPDATED: 'inventory.adjust', ITEM_ISSUED: 'inventory.issue', ITEM_RETURNED: 'inventory.return', INVENTORY_COUNT_SUBMITTED: 'inventory.count', RECORD_CORRECTED: 'inventory.adjust', CONFLICT_RESOLVED: 'conflicts.resolve', CADET_CREATED: 'cadets.manage', CADET_UPDATED: 'cadets.manage', BUNDLE_CREATED: 'bundles.manage', BUNDLE_UPDATED: 'bundles.manage', BUNDLE_DEACTIVATED: 'bundles.manage', STILL_NEEDED_ADDED: 'cadets.manage', STILL_NEEDED_UPDATED: 'cadets.manage', STILL_NEEDED_CANCELLED: 'cadets.manage', STILL_NEEDED_FULFILLED: 'cadets.manage' } as Partial<Record<SignedArgusEvent['eventType'], ArgusPermission>>)[type]
const unsigned = (event: SignedArgusEvent) => { const rest: Partial<SignedArgusEvent> = { ...event }; delete rest.signature; return canonicalize(rest) }
export const MAX_SUPPLY_LINE_QUANTITY = 100

export class ArgusReplica {
  online = true
  private syncing?: Promise<void>
  constructor(readonly repository: ArgusRepository, private identity: ArgusIdentityProvider, private authorization: AuthorizationService, private provider: MockSyncProvider, readonly organizationId = 'argus-demo-organization') {}
  async initialize(items: Array<Pick<InventoryProjection, 'entityId' | 'name' | 'onHand' | 'version'> & Partial<Omit<InventoryProjection, 'entityId' | 'name' | 'onHand' | 'version' | 'appliedEventIds'>>> = []) {
    await this.repository.initialize()
    await this.repository.transaction(s => { if (!s.inventory.length) s.inventory = items.map(item => ({ category: 'Uncategorized', variant: 'No variant', niin: 'Not assigned', issued: 0, countIncrement: 1, active: true, ...item, appliedEventIds: [] })); for (const source of FACTORY_BUNDLES) if (!s.bundles.some(b => b.bundleId === source.bundleId)) { const version = structuredClone(source); version.lines = version.lines.map(line => ({ ...line, itemId: s.inventory.find(item => item.name === line.displayLabel)?.entityId })); s.bundles.push({ bundleId: version.bundleId, currentVersion: 1, versions: [version], appliedEventIds: [version.eventId] }) } })
  }
  private async signed(input: Omit<UnsignedArgusEvent, 'protocol' | 'protocolVersion' | 'organizationId' | 'eventVersion' | 'eventId' | 'actorPublicIdentity' | 'timestamp'> & { eventId?: string; timestamp?: string }) {
    const event = { protocol: 'ARGUS' as const, protocolVersion: 1 as const, organizationId: this.organizationId, eventVersion: 1 as const, eventId: input.eventId ?? crypto.randomUUID(), eventType: input.eventType, entityId: input.entityId, actorPublicIdentity: await this.identity.getPublicIdentity(), timestamp: input.timestamp ?? new Date().toISOString(), ...(input.baseVersion === undefined ? {} : { baseVersion: input.baseVersion }), payload: input.payload }
    return { ...event, signature: await this.identity.sign(canonicalize(event)) }
  }
  async issue(entityId: string, quantity: number, options: { eventId?: string; timestamp?: string } = {}) {
    const state = await this.repository.snapshot(); const item = state.inventory.find(i => i.entityId === entityId)
    if (!item) throw new Error('Inventory item was not found.'); if (quantity <= 0 || item.onHand < quantity) throw new Error('Insufficient inventory.')
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.issue', options.timestamp)
    const event = await this.signed({ eventType: 'ITEM_ISSUED', entityId, baseVersion: item.version, payload: { quantity }, ...options })
    await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async issueTransaction(input: { transactionId: string; cadetId: string; lines: Array<{ lineId: string; itemId: string; quantity: number; requirementId?: string }>; missingLines?: MissingIssueLine[]; bundleId?: string; bundleVersion?: number }, options: { eventId?: string; timestamp?: string } = {}) {
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.issue', options.timestamp)
    const state = await this.repository.snapshot(), cadet = state.cadets.find(candidate => candidate.cadetId === input.cadetId)
    if (!cadet) throw new Error('Cadet was not found.'); if (cadet.status !== 'ACTIVE') throw new Error('Inactive cadets cannot receive inventory.')
    this.validateDraftIdentity(input.transactionId, input.lines, input.missingLines)
    const retry = options.eventId ? state.events.find(record => record.event.eventId === options.eventId) : undefined
    if (retry) { const prior = retry.event.payload as { transactionId?:unknown;cadetId?:unknown;lines?:Array<{lineId:string;itemId:string;quantity:number}> }; if (retry.event.eventType !== 'ITEM_ISSUED' || prior.transactionId !== input.transactionId || prior.cadetId !== input.cadetId || canonicalize(prior.lines?.map(({lineId,itemId,quantity})=>({lineId,itemId,quantity}))??[]) !== canonicalize(input.lines.map(({lineId,itemId,quantity})=>({lineId,itemId,quantity})))) throw new Error('Event ID collision detected.'); return retry.event }
    const lines = input.lines.map(line => { const item = state.inventory.find(candidate => candidate.entityId === line.itemId); if (!item) throw new Error('Inventory item was not found.'); if (!item.active) throw new Error(`${item.name} · ${item.variant} is inactive.`); this.validateQuantity(line.quantity); if (item.onHand < line.quantity) throw new Error(`Stock changed before confirmation. ${item.name} · ${item.variant} is no longer available.`); return { ...line, label: item.name, variant: item.variant, baseVersion: item.version } })
    const bundle = input.bundleId ? state.bundles.find(candidate => candidate.bundleId === input.bundleId)?.versions.find(version => version.version === input.bundleVersion) : undefined
    if (input.bundleId && !bundle) throw new Error('The selected bundle version is no longer valid.')
    const event = await this.signed({ eventType: 'ITEM_ISSUED', entityId: input.transactionId, payload: { ...input, lines, ...(bundle ? { bundleSnapshot: structuredClone(bundle) } : {}) }, ...options })
    await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async returnTransaction(input: { transactionId: string; cadetId: string; lines: Array<{ lineId: string; propertyId: string; quantity: number }> }, options: { eventId?: string; timestamp?: string } = {}) {
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.return', options.timestamp)
    const state = await this.repository.snapshot(), cadet = state.cadets.find(candidate => candidate.cadetId === input.cadetId); if (!cadet) throw new Error('Cadet was not found.')
    this.validateDraftIdentity(input.transactionId, input.lines)
    const retry = options.eventId ? state.events.find(record => record.event.eventId === options.eventId) : undefined
    if (retry) { const prior = retry.event.payload as { transactionId?:unknown;cadetId?:unknown;lines?:Array<{lineId:string;propertyId:string;quantity:number}> }; if (retry.event.eventType !== 'ITEM_RETURNED' || prior.transactionId !== input.transactionId || prior.cadetId !== input.cadetId || canonicalize(prior.lines?.map(({lineId,propertyId,quantity})=>({lineId,propertyId,quantity}))??[]) !== canonicalize(input.lines)) throw new Error('Event ID collision detected.'); return retry.event }
    const lines = input.lines.map(line => { const property = cadet.currentProperty.find(candidate => candidate.propertyId === line.propertyId); if (!property) throw new Error('This cadet no longer has the selected item.'); this.validateQuantity(line.quantity); if (line.quantity > property.quantity) throw new Error('Return quantity exceeds current property.'); const item = state.inventory.find(candidate => candidate.entityId === property.itemId); if (!item) throw new Error('Inventory mapping for returned property was not found.'); return { ...line, itemId: item.entityId, label: item.name, variant: item.variant, baseVersion: item.version } })
    const event = await this.signed({ eventType: 'ITEM_RETURNED', entityId: input.transactionId, payload: { transactionId: input.transactionId, cadetId: input.cadetId, lines }, ...options })
    await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  private validateDraftIdentity(transactionId: string, lines: Array<{ lineId: string; itemId?: string }>, missing: MissingIssueLine[] = []) { if (!transactionId || (!lines.length && !missing.length)) throw new Error('Supply transaction is empty.'); const ids = [...lines, ...missing].map(line => line.lineId); if (ids.some(id => !id) || new Set(ids).size !== ids.length) throw new Error('Supply transaction line IDs must be unique.'); const items = lines.map(line => line.itemId).filter(Boolean); if (new Set(items).size !== items.length) throw new Error('Duplicate inventory variants are not allowed in one transaction.') }
  private validateQuantity(quantity: number) { if (!Number.isInteger(quantity) || quantity < 1 || quantity > MAX_SUPPLY_LINE_QUANTITY) throw new Error(`Quantity must be a whole number from 1 to ${MAX_SUPPLY_LINE_QUANTITY}.`) }
  async returnItem(entityId: string, quantity: number, options: { eventId?: string; timestamp?: string } = {}) {
    const state = await this.repository.snapshot(); const item = state.inventory.find(i => i.entityId === entityId)
    if (!item) throw new Error('Inventory item was not found.'); if (!Number.isInteger(quantity) || quantity <= 0 || (item.issued ?? 0) < quantity) throw new Error('Invalid return quantity.')
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.return', options.timestamp)
    const event = await this.signed({ eventType: 'ITEM_RETURNED', entityId, baseVersion: item.version, payload: { quantity }, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async submitCount(entityId: string, countedQuantity: number, sessionId: string, options: { eventId?: string; timestamp?: string } = {}) {
    const state = await this.repository.snapshot(); const item = state.inventory.find(i => i.entityId === entityId)
    if (!item || !Number.isInteger(countedQuantity) || countedQuantity < 0) throw new Error('Invalid physical count.')
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.count', options.timestamp)
    const event = await this.signed({ eventType: 'INVENTORY_COUNT_SUBMITTED', entityId, baseVersion: item.version, payload: { sessionId, expectedQuantity: item.onHand, countedQuantity, discrepancy: countedQuantity - item.onHand }, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async createInventoryItem(input: Omit<InventoryProjection, 'entityId' | 'version' | 'appliedEventIds' | 'issued'> & { entityId?: string; issued?: number }, options: { eventId?: string; timestamp?: string } = {}) {
    if (!input.name.trim() || !input.category.trim() || !Number.isInteger(input.onHand) || input.onHand < 0 || !Number.isInteger(input.countIncrement) || input.countIncrement < 1) throw new Error('Inventory item details are invalid.')
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.create', options.timestamp)
    const id = input.entityId ?? `item_${crypto.randomUUID()}`; if ((await this.repository.snapshot()).inventory.some(item => item.entityId === id)) throw new Error('Inventory item ID already exists.')
    const event = await this.signed({ eventType: 'INVENTORY_ITEM_CREATED', entityId: id, payload: { ...input, issued: input.issued ?? 0 }, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async updateInventoryItem(entityId: string, changes: Partial<Pick<InventoryProjection, 'name'|'category'|'variant'|'niin'|'reorderAt'|'countIncrement'|'active'>>, options: { eventId?: string; timestamp?: string } = {}) {
    const item = (await this.repository.snapshot()).inventory.find(candidate => candidate.entityId === entityId); if (!item) throw new Error('Inventory item was not found.')
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.adjust', options.timestamp)
    const event = await this.signed({ eventType: 'INVENTORY_ITEM_UPDATED', entityId, baseVersion: item.version, payload: changes, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async correct(originalEventId: string, entityId: string, field: string, value: unknown, reason: string) {
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'inventory.adjust')
    const event = await this.signed({ eventType: 'RECORD_CORRECTED', entityId, payload: { originalEventId, field, value, reason } }); await this.persistLocal(event); return event
  }
  async createCadet(input: Pick<CadetProjection, 'fullName' | 'gender' | 'nsLevel' | 'status'> & { sizes?: Record<string, string> }, options: { eventId?: string; timestamp?: string } = {}) {
    const value = { ...input, sizes: input.sizes ?? {} }; validateCadet(value); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'cadets.manage', options.timestamp)
    const id = `cadet_${crypto.randomUUID()}`, event = await this.signed({ eventType: 'CADET_CREATED', entityId: id, payload: value, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async updateCadet(cadetId: string, changes: Partial<Pick<CadetProjection, 'fullName' | 'gender' | 'nsLevel' | 'status' | 'sizes'>>, options: { eventId?: string; timestamp?: string } = {}) {
    const cadet = (await this.repository.snapshot()).cadets.find(c => c.cadetId === cadetId); if (!cadet) throw new Error('Cadet was not found.'); const next = { ...cadet, ...changes }; validateCadet(next); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'cadets.manage', options.timestamp)
    const event = await this.signed({ eventType: 'CADET_UPDATED', entityId: cadetId, baseVersion: cadet.version, payload: changes, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async updateBundle(bundleId: string, input: Omit<BundleVersionProjection, 'bundleId' | 'version' | 'createdAt' | 'actorPublicIdentity' | 'priorVersion' | 'eventId'>, options: { eventId?: string; timestamp?: string } = {}) {
    const current = (await this.repository.snapshot()).bundles.find(b => b.bundleId === bundleId); if (!current) throw new Error('Bundle was not found.'); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'bundles.manage', options.timestamp); validateBundle({ ...input, version: current.currentVersion + 1 })
    const event = await this.signed({ eventType: 'BUNDLE_UPDATED', entityId: bundleId, baseVersion: current.currentVersion, payload: input, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async createBundle(bundleId: string, input: Omit<BundleVersionProjection, 'bundleId' | 'version' | 'createdAt' | 'actorPublicIdentity' | 'priorVersion' | 'eventId'>, options: { eventId?: string; timestamp?: string } = {}) { const state = await this.repository.snapshot(); if (!bundleId || state.bundles.some(b => b.bundleId === bundleId)) throw new Error('Bundle ID is invalid or already exists.'); validateBundle({ ...input, version: 1 }, state.inventory); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'bundles.manage', options.timestamp); const event = await this.signed({ eventType: 'BUNDLE_CREATED', entityId: bundleId, payload: input, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event }
  async addStillNeeded(input: Omit<StillNeededProjection, 'requirementId' | 'version' | 'appliedEventIds' | 'updatedAt'> & { requirementId?: string }, options: { eventId?: string; timestamp?: string } = {}) {
    validateRequirement(input); const state = await this.repository.snapshot(); if (!state.cadets.some(c => c.cadetId === input.cadetId)) throw new Error('Cadet was not found.'); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'cadets.manage', options.timestamp); const id = input.requirementId ?? `need_${crypto.randomUUID()}`
    const event = await this.signed({ eventType: 'STILL_NEEDED_ADDED', entityId: id, payload: input, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event
  }
  async updateStillNeeded(requirementId: string, changes: Partial<Pick<StillNeededProjection,'displayLabel'|'itemId'|'size'|'quantityNeeded'|'quantityFulfilled'|'status'>>, options: { eventId?: string; timestamp?: string } = {}) { const requirement = (await this.repository.snapshot()).stillNeeded.find(r => r.requirementId === requirementId); if (!requirement) throw new Error('Still Needed requirement was not found.'); const next = { ...requirement, ...changes }; validateRequirement(next); const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'cadets.manage', options.timestamp); const type = next.status === 'CANCELLED' ? 'STILL_NEEDED_CANCELLED' : next.status === 'FULFILLED' ? 'STILL_NEEDED_FULFILLED' : 'STILL_NEEDED_UPDATED'; const event = await this.signed({ eventType: type, entityId: requirementId, baseVersion: requirement.version, payload: changes, ...options }); await this.persistLocal(event); if (this.online) await this.sync(); return event }
  async resolve(conflictId: string, resolution: string) {
    const actor = await this.identity.getPublicIdentity(); this.authorization.require(actor, 'conflicts.resolve')
    const state = await this.repository.snapshot(); const conflict = state.conflicts.find(c => c.id === conflictId && c.status === 'OPEN'); if (!conflict) throw new Error('Open conflict was not found.')
    const event = await this.signed({ eventType: 'CONFLICT_RESOLVED', entityId: conflict.entityId, payload: { conflictId, resolution } }); await this.persistLocal(event); return event
  }
  private apply(state: RepositoryState, event: SignedArgusEvent) {
    const duplicateEvent = state.events.find(record => record.event.eventId === event.eventId)
    if (duplicateEvent) { if (canonicalize(duplicateEvent.event) !== canonicalize(event)) throw new Error('Event ID collision detected.'); return }
    const permission = permissionFor(event.eventType); if (permission) this.authorization.require(event.actorPublicIdentity, permission, event.timestamp)
    if (event.eventType === 'INVENTORY_ITEM_CREATED') { const value = event.payload as unknown as Omit<InventoryProjection, 'entityId'|'version'|'appliedEventIds'>; if (state.inventory.some(item => item.entityId === event.entityId)) throw new Error('Inventory item ID already exists.'); state.inventory.push({ ...value, entityId: event.entityId, version: 1, appliedEventIds: [event.eventId] }) }
    if (event.eventType === 'INVENTORY_ITEM_UPDATED') { const item = state.inventory.find(candidate => candidate.entityId === event.entityId); if (!item) throw new Error('Inventory projection is missing.'); if (event.baseVersion !== item.version) this.addConflict(state, event, 'Concurrent inventory metadata updates require reconciliation.'); else { Object.assign(item, event.payload); item.version++; item.appliedEventIds.push(event.eventId) } }
    if ((event.eventType === 'ITEM_ISSUED' || event.eventType === 'ITEM_RETURNED') && Array.isArray(event.payload.lines)) this.applySupplyTransaction(state, event)
    else if (event.eventType === 'ITEM_ISSUED' || event.eventType === 'ITEM_RETURNED') {
      const item = state.inventory.find(i => i.entityId === event.entityId); if (!item) throw new Error('Inventory projection is missing.')
      if (item.appliedEventIds.includes(event.eventId)) return
      const quantity = event.payload.quantity; if (!Number.isInteger(quantity) || Number(quantity) <= 0) throw new Error('Corrupted event quantity.')
      const delta = event.eventType === 'ITEM_ISSUED' ? -Number(quantity) : Number(quantity)
      if (event.baseVersion !== item.version || item.onHand + delta < 0 || item.issued - delta < 0) {
        const related = state.events.filter(e => e.event.entityId === event.entityId && e.event.baseVersion === event.baseVersion && e.event.eventType === 'ITEM_ISSUED').map(e => e.event.eventId)
        const conflict: ConflictRecord = { id: `conflict:${[...related, event.eventId].sort().join(':')}`, entityId: event.entityId, eventIds: [...related, event.eventId], status: 'OPEN', reason: `Concurrent events attempted to consume unavailable ${item.name}.` }
        if (!state.conflicts.some(c => c.id === conflict.id)) state.conflicts.push(conflict)
      } else { item.onHand += delta; item.issued = Math.max(0, (item.issued ?? 0) - delta); item.version += 1; item.appliedEventIds.push(event.eventId) }
    }
    if (event.eventType === 'INVENTORY_COUNT_SUBMITTED') { const item = state.inventory.find(i => i.entityId === event.entityId); const counted = event.payload.countedQuantity; if (!item || !Number.isInteger(counted) || Number(counted) < 0) throw new Error('Corrupted count event.'); if (event.baseVersion !== item.version) this.addConflict(state, event, 'Physical count was based on a stale inventory version.'); else { item.onHand = Number(counted); item.version++; item.appliedEventIds.push(event.eventId) } }
    if (event.eventType === 'CADET_CREATED') { const value = event.payload as unknown as Pick<CadetProjection, 'fullName'|'gender'|'nsLevel'|'status'|'sizes'>; validateCadet(value); if (state.cadets.some(c => c.cadetId === event.entityId)) throw new Error('Cadet ID already exists.'); state.cadets.push({ cadetId: event.entityId, ...value, currentProperty: [], createdAt: event.timestamp, updatedAt: event.timestamp, version: 1, appliedEventIds: [event.eventId] }) }
    if (event.eventType === 'CADET_UPDATED') { const cadet = state.cadets.find(c => c.cadetId === event.entityId); if (!cadet) throw new Error('Cadet projection is missing.'); if (event.baseVersion !== cadet.version) this.addConflict(state, event, 'Concurrent cadet updates require reconciliation.'); else { const next = { ...cadet, ...event.payload }; validateCadet(next); Object.assign(cadet, event.payload, { updatedAt: event.timestamp, version: cadet.version + 1 }); cadet.appliedEventIds.push(event.eventId) } }
    if (event.eventType === 'BUNDLE_UPDATED') { const bundle = state.bundles.find(b => b.bundleId === event.entityId); if (!bundle) throw new Error('Bundle projection is missing.'); if (event.baseVersion !== bundle.currentVersion) this.addConflict(state, event, 'Concurrent bundle edits require reconciliation.'); else { const version = { ...(event.payload as unknown as Omit<BundleVersionProjection,'bundleId'|'version'|'createdAt'|'actorPublicIdentity'|'priorVersion'|'eventId'>), bundleId: bundle.bundleId, version: bundle.currentVersion + 1, createdAt: event.timestamp, actorPublicIdentity: event.actorPublicIdentity, priorVersion: bundle.currentVersion, eventId: event.eventId }; validateBundle(version); bundle.versions.push(version); bundle.currentVersion++; bundle.appliedEventIds.push(event.eventId) } }
    if (event.eventType === 'BUNDLE_CREATED') { const value = event.payload as unknown as Omit<BundleVersionProjection,'bundleId'|'version'|'createdAt'|'actorPublicIdentity'|'priorVersion'|'eventId'>; const version = { ...value, bundleId: event.entityId, version: 1, createdAt: event.timestamp, actorPublicIdentity: event.actorPublicIdentity, eventId: event.eventId }; validateBundle(version, state.inventory); if (state.bundles.some(b => b.bundleId === event.entityId)) throw new Error('Bundle ID already exists.'); state.bundles.push({ bundleId: event.entityId, currentVersion: 1, versions: [version], appliedEventIds: [event.eventId] }) }
    if (event.eventType === 'STILL_NEEDED_ADDED') { const value = event.payload as unknown as Omit<StillNeededProjection,'requirementId'|'version'|'appliedEventIds'|'updatedAt'>; validateRequirement(value); if (!state.cadets.some(c => c.cadetId === value.cadetId)) throw new Error('Cadet projection is missing.'); state.stillNeeded.push({ ...value, requirementId: event.entityId, updatedAt: event.timestamp, version: 1, appliedEventIds: [event.eventId] }) }
    if (['STILL_NEEDED_UPDATED','STILL_NEEDED_CANCELLED','STILL_NEEDED_FULFILLED'].includes(event.eventType)) { const requirement = state.stillNeeded.find(r => r.requirementId === event.entityId); if (!requirement) throw new Error('Still Needed projection is missing.'); if (event.baseVersion !== requirement.version) this.addConflict(state, event, 'Concurrent Still Needed updates require reconciliation.'); else { const next = { ...requirement, ...event.payload }; validateRequirement(next); Object.assign(requirement, event.payload, { updatedAt: event.timestamp, version: requirement.version + 1 }); requirement.appliedEventIds.push(event.eventId) } }
    if (event.eventType === 'CONFLICT_RESOLVED') { const conflict = state.conflicts.find(c => c.id === event.payload.conflictId); if (conflict) { conflict.status = 'RESOLVED'; conflict.resolutionEventId = event.eventId } }
    state.events.push({ event, syncStatus: 'SYNCHRONIZED', auditStatus: 'PENDING', receivedAt: new Date().toISOString() })
  }
  private applySupplyTransaction(state: RepositoryState, event: SignedArgusEvent) {
    const payload = event.payload as { transactionId?: unknown; cadetId?: unknown; lines?: unknown; missingLines?: unknown; bundleId?: unknown; bundleVersion?: unknown; bundleSnapshot?: unknown }
    if (typeof payload.transactionId !== 'string' || payload.transactionId !== event.entityId || typeof payload.cadetId !== 'string' || !Array.isArray(payload.lines)) throw new Error('Malformed supply transaction event.')
    const existing = state.transactions.find(transaction => transaction.transactionId === payload.transactionId)
    if (existing) { if (existing.eventId !== event.eventId) throw new Error('Transaction ID collision detected.'); return }
    const cadet = state.cadets.find(candidate => candidate.cadetId === payload.cadetId); if (!cadet) throw new Error('Cadet projection is missing.')
    const lines = payload.lines as SupplyTransactionLine[], missing = payload.missingLines === undefined ? [] : payload.missingLines as MissingIssueLine[]
    if (!Array.isArray(missing)) throw new Error('Malformed missing-lines payload.')
    this.validateDraftIdentity(payload.transactionId, lines, missing)
    const resolved = lines.map(line => { this.validateQuantity(line.quantity); if (!Number.isInteger(line.baseVersion) || !line.itemId || !line.label || !line.variant) throw new Error('Malformed supply transaction line.'); const item = state.inventory.find(candidate => candidate.entityId === line.itemId); if (!item) throw new Error('Inventory projection is missing.'); if (line.label !== item.name || line.variant !== item.variant) throw new Error('Inventory snapshot does not match the referenced SKU.'); return { line, item } })
    for (const line of missing) { if (!line.required || !line.lineId || !line.label) throw new Error('Malformed missing issue line.'); this.validateQuantity(line.quantity); if (line.itemId) { const item = state.inventory.find(candidate => candidate.entityId === line.itemId); if (!item || line.variant !== item.variant) throw new Error('Missing line does not match the referenced SKU.') } }
    if (event.eventType === 'ITEM_ISSUED' && cadet.status !== 'ACTIVE') throw new Error('Inactive cadets cannot receive inventory.')
    const bundleSnapshot = payload.bundleSnapshot as import('./types').BundleVersionProjection | undefined
    if ((payload.bundleId === undefined) !== (payload.bundleVersion === undefined) || (payload.bundleId !== undefined && (typeof payload.bundleId !== 'string' || !Number.isInteger(payload.bundleVersion) || !bundleSnapshot || bundleSnapshot.bundleId !== payload.bundleId || bundleSnapshot.version !== payload.bundleVersion))) throw new Error('Malformed bundle transaction snapshot.')
    if (event.eventType === 'ITEM_ISSUED' && resolved.some(({ line, item }) => !item.active || item.version !== line.baseVersion || item.onHand < line.quantity)) { this.addSupplyConflict(state, event, payload.cadetId, resolved); return }
    if (event.eventType === 'ITEM_RETURNED' && resolved.some(({ line, item }) => { const property = cadet.currentProperty.find(candidate => candidate.propertyId === line.propertyId); return item.version !== line.baseVersion || !property || property.itemId !== item.entityId || property.quantity < line.quantity })) { this.addSupplyConflict(state, event, payload.cadetId, resolved, 'Concurrent return transaction referenced stale inventory or property.'); return }
    if (event.eventType === 'ITEM_ISSUED') {
      for (const { line, item } of resolved) { item.onHand -= line.quantity; item.issued += line.quantity; item.version++; item.appliedEventIds.push(event.eventId); const requirement = state.stillNeeded.find(candidate => candidate.cadetId === cadet.cadetId && candidate.itemId === item.entityId && candidate.size === item.variant && !['FULFILLED','CANCELLED'].includes(candidate.status) && (!line.requirementId || candidate.requirementId === line.requirementId)); if (requirement) { requirement.quantityFulfilled = Math.min(requirement.quantityNeeded, requirement.quantityFulfilled + line.quantity); requirement.status = requirement.quantityFulfilled === requirement.quantityNeeded ? 'FULFILLED' : 'PARTIALLY_FULFILLED'; requirement.updatedAt = event.timestamp; requirement.version++; requirement.appliedEventIds.push(event.eventId) } cadet.currentProperty.push({ propertyId: `${event.eventId}:${line.lineId}`, itemId: item.entityId, label: item.name, variant: item.variant, quantity: line.quantity, issuedAt: event.timestamp, issueEventId: event.eventId, issueTransactionId: payload.transactionId, bundleId: payload.bundleId as string|undefined, bundleVersion: payload.bundleVersion as number|undefined }) }
      for (const line of missing) { const existingNeed = state.stillNeeded.find(requirement => requirement.cadetId === cadet.cadetId && requirement.itemId === line.itemId && requirement.size === line.variant && requirement.displayLabel === line.label && requirement.source === 'INCOMPLETE_ISSUE' && !['FULFILLED','CANCELLED'].includes(requirement.status)); if (existingNeed) { existingNeed.quantityNeeded += line.quantity; existingNeed.relatedTransactionIds = [...new Set([...(existingNeed.relatedTransactionIds ?? []), payload.transactionId])]; existingNeed.updatedAt = event.timestamp; existingNeed.version++; existingNeed.appliedEventIds.push(event.eventId) } else state.stillNeeded.push({ requirementId: `need:${event.eventId}:${line.lineId}`, cadetId: cadet.cadetId, itemId: line.itemId, displayLabel: line.label, size: line.variant, quantityNeeded: line.quantity, quantityFulfilled: 0, status: 'OPEN', firstNeededAt: event.timestamp, updatedAt: event.timestamp, source: 'INCOMPLETE_ISSUE', relatedTransactionIds: [payload.transactionId], relatedBundleId: payload.bundleId as string|undefined, bundleVersion: payload.bundleVersion as number|undefined, version: 1, appliedEventIds: [event.eventId] }) }
    } else for (const { line, item } of resolved) { const property = cadet.currentProperty.find(candidate => candidate.propertyId === line.propertyId)!; property.quantity -= line.quantity; if (!property.quantity) cadet.currentProperty = cadet.currentProperty.filter(candidate => candidate.propertyId !== property.propertyId); item.onHand += line.quantity; item.issued = Math.max(0, item.issued - line.quantity); item.version++; item.appliedEventIds.push(event.eventId) }
    cadet.version++; cadet.updatedAt = event.timestamp; cadet.appliedEventIds.push(event.eventId)
    state.transactions.push({ transactionId: payload.transactionId, transactionType: event.eventType === 'ITEM_ISSUED' ? 'ISSUE' : 'RETURN', cadetId: cadet.cadetId, actorId: event.actorPublicIdentity, createdAt: event.timestamp, eventId: event.eventId, bundleId: payload.bundleId as string|undefined, bundleVersion: payload.bundleVersion as number|undefined, bundleSnapshot, lines: structuredClone(lines), missingLines: structuredClone(missing) })
  }
  private addSupplyConflict(state: RepositoryState, event: SignedArgusEvent, cadetId: string, resolved: Array<{line:SupplyTransactionLine;item:InventoryProjection}>, reason = 'Concurrent issue transaction attempted to consume unavailable inventory.') { const inventoryItemIds = resolved.filter(({line,item}) => item.version !== line.baseVersion || item.onHand < line.quantity).map(({item}) => item.entityId); const related = state.events.filter(record => ['ITEM_ISSUED','ITEM_RETURNED'].includes(record.event.eventType) && Array.isArray(record.event.payload.lines) && (record.event.payload.lines as SupplyTransactionLine[]).some(line => inventoryItemIds.includes(line.itemId) && resolved.some(candidate => candidate.line.itemId === line.itemId && candidate.line.baseVersion === line.baseVersion))).map(record => record.event.eventId); const eventIds = [...new Set([...related,event.eventId])].sort(); const entityId = inventoryItemIds[0] ?? event.entityId; const conflict: ConflictRecord = { id:`conflict:${eventIds.join(':')}`, entityId, eventIds, status:'OPEN', reason, transactionId:event.entityId, inventoryItemIds, cadetId }; if(!state.conflicts.some(candidate=>candidate.id===conflict.id))state.conflicts.push(conflict) }
  private addConflict(state: RepositoryState, event: SignedArgusEvent, reason: string) { const related = state.events.filter(e => e.event.entityId === event.entityId && e.event.baseVersion === event.baseVersion).map(e => e.event.eventId); const ids = [...related, event.eventId].sort(); const conflict = { id: `conflict:${ids.join(':')}`, entityId: event.entityId, eventIds: ids, status: 'OPEN' as const, reason }; if (!state.conflicts.some(c => c.id === conflict.id)) state.conflicts.push(conflict) }
  private async persistLocal(event: SignedArgusEvent) { await this.repository.transaction(state => { const before = state.events.length; this.apply(state, event); if (state.events.length === before) return; const stored = state.events.find(e => e.event.eventId === event.eventId)!; stored.syncStatus = 'QUEUED'; if (!state.outbox.some(record => record.eventId === event.eventId)) state.outbox.push({ eventId: event.eventId, attempts: 0, status: 'QUEUED' }) }) }
  async receive(event: SignedArgusEvent) {
    if (event.protocol !== 'ARGUS' || event.protocolVersion !== 1 || event.eventVersion !== 1 || event.organizationId !== this.organizationId || !event.eventId || !event.actorPublicIdentity || !event.signature || !event.payload || typeof event.payload !== 'object') throw new Error('Malformed or unsupported distributed event.')
    if (!(await this.identity.verify(unsigned(event), event.signature, event.actorPublicIdentity))) throw new Error('Invalid event signature.')
    await this.repository.transaction(state => this.apply(state, event))
  }
  sync() { return this.syncing ?? (this.syncing = this.runSync().finally(() => { this.syncing = undefined })) }
  private async runSync() {
    if (!this.online) return
    const before = await this.repository.snapshot()
    for (const record of before.outbox) {
      const event = before.events.find(e => e.event.eventId === record.eventId)!.event
      try { await this.provider.publish(event); await this.repository.transaction(s => { s.outbox = s.outbox.filter(o => o.eventId !== event.eventId); const stored = s.events.find(e => e.event.eventId === event.eventId); if (stored) stored.syncStatus = 'SYNCHRONIZED' }) }
      catch (error) { await this.repository.transaction(s => { const out = s.outbox.find(o => o.eventId === event.eventId); if (out) { out.status = 'FAILED'; out.attempts++; out.lastError = error instanceof Error ? error.message : 'Sync failed' }; const stored = s.events.find(e => e.event.eventId === event.eventId); if (stored) stored.syncStatus = 'FAILED' }) }
    }
    for (const event of await this.provider.pull()) await this.receive(event)
  }
  async snapshot() { return this.repository.snapshot() }
}
