import { useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, PackagePlus, Search, X } from 'lucide-react'
import type { DistributedAppController } from '../distributed/appIntegration'
import type { RepositoryState } from '../storage/repository'
import type { AppData } from '../types'
import { bundleSuggestions, cadetReadiness, searchCadets } from '../stage3/domain'

type Props = { mode: 'ISSUE' | 'RETURN'; state: RepositoryState; data: AppData; controller: DistributedAppController; onClose: () => void; onChanged: (state: RepositoryState) => void }
type DraftLine = { lineId: string; itemId: string; label: string; size?: string; quantity: number; included: boolean; required: boolean; propertyId?: string }

export function SupplyWorkflow({ mode, state, data, controller, onClose, onChanged }: Props) {
  const [step, setStep] = useState(0), [query, setQuery] = useState(''), [cadetId, setCadetId] = useState(''), [bundleId, setBundleId] = useState('individual'), [lines, setLines] = useState<DraftLine[]>([]), [review, setReview] = useState(false), [busy, setBusy] = useState(false), [complete, setComplete] = useState(false), [error, setError] = useState('')
  const transactionId = useRef(`supply:${crypto.randomUUID()}`), eventId = useRef(`event:${crypto.randomUUID()}`)
  const cadet = state.cadets.find(c => c.cadetId === cadetId), activeCadets = useMemo(() => searchCadets(state.cadets, query, 'ACTIVE'), [state.cadets, query])
  const inventory = state.inventory.map(item => ({ ...item, detail: data.inventory.find(i => i.id === item.entityId) }))
  const selectedBundle = state.bundles.find(b => b.bundleId === bundleId)?.versions.find(v => v.version === state.bundles.find(b => b.bundleId === bundleId)?.currentVersion)
  const recommendation = cadet ? bundleSuggestions(cadet.gender) : []
  const chooseBundle = (id: string) => { setBundleId(id); const version = state.bundles.find(b => b.bundleId === id)?.versions.at(-1); setLines(version?.lines.map(line => { const match = inventory.find(i => i.entityId === line.itemId) ?? inventory.find(i => i.name.toLowerCase().includes(line.displayLabel.toLowerCase()) || line.displayLabel.toLowerCase().includes(i.name.toLowerCase())); return { lineId: line.lineId, itemId: match?.entityId ?? '', label: line.displayLabel, size: line.supportsSizing ? (cadet?.sizes[line.displayLabel] ?? match?.detail?.size) : undefined, quantity: line.defaultQuantity, included: line.required || Boolean(match), required: line.required } }) ?? []); setStep(2) }
  const addIndividual = (itemId: string) => { const item = inventory.find(i => i.entityId === itemId)!; setLines(current => current.some(l => l.itemId === itemId) ? current : [...current, { lineId: crypto.randomUUID(), itemId, label: item.name, size: item.detail?.size === 'No size' ? undefined : item.detail?.size, quantity: 1, included: true, required: false }]) }
  const ready = lines.filter(l => l.included && l.itemId && (state.inventory.find(i => i.entityId === l.itemId)?.onHand ?? 0) >= l.quantity), missing = lines.filter(l => l.required && (!l.included || !l.itemId || (state.inventory.find(i => i.entityId === l.itemId)?.onHand ?? 0) < l.quantity))
  const confirm = async () => { if (busy) return; setBusy(true); setError(''); try { if (mode === 'ISSUE') await controller.issueTransaction({ transactionId: transactionId.current, cadetId, lines: ready.map(({ lineId,itemId,label,size,quantity }) => ({ lineId,itemId,label,size,quantity })), missingLines: missing.map(({ lineId,itemId,label,size,quantity }) => ({ lineId,itemId: itemId || undefined,label,size,quantity,required:true })), ...(selectedBundle ? { bundleId: selectedBundle.bundleId, bundleVersion: selectedBundle.version } : {}) }, { eventId: eventId.current }); else await controller.returnTransaction({ transactionId: transactionId.current, cadetId, lines: lines.filter(l => l.included).map(l => ({ lineId:l.lineId, propertyId:l.propertyId!, quantity:l.quantity })) }, { eventId:eventId.current }); const next = await controller.technicalState(); onChanged(next); setComplete(true) } catch (reason) { setError(reason instanceof Error ? reason.message : 'The transaction could not be completed.'); setReview(false) } finally { setBusy(false) } }
  if (complete) return <Shell title={`${mode === 'ISSUE' ? 'Issue' : 'Return'} Complete`} onClose={onClose}><div className="workflow-success"><Check/><h3>{mode === 'ISSUE' ? 'Issue Complete' : 'Return Complete'}</h3><p>Saved locally · {state.outbox.length ? 'Sync queued' : 'Synchronization requested'}</p><button className="primary-button" onClick={onClose}>Done</button></div></Shell>
  return <Shell title={mode === 'ISSUE' ? 'Issue property' : 'Return property'} onClose={onClose}>
    <ol className="workflow-steps" aria-label="Workflow progress">{['Cadet',mode === 'ISSUE'?'Type':'Property','Configure','Review'].map((label,i)=><li className={i<=step?'active':''} key={label}>{i+1}<span>{label}</span></li>)}</ol>
    {error && <div className="workflow-error" role="alert">{error}</div>}
    {step===0 && <section><h3>Select Cadet</h3><label className="workflow-search"><Search/><input autoFocus aria-label="Search active cadets" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search active cadets…"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X/></button>}</label><div className="workflow-list">{activeCadets.map(c=>{const needs=state.stillNeeded.filter(n=>n.cadetId===c.cadetId);return <button key={c.cadetId} onClick={()=>{setCadetId(c.cadetId);setStep(1);if(mode==='RETURN')setLines(c.currentProperty.map(p=>({lineId:crypto.randomUUID(),itemId:p.itemId,label:p.label,size:p.size,quantity:p.quantity,included:false,required:false,propertyId:p.propertyId})))}}><b>{c.fullName}</b><small>{c.nsLevel} · {c.gender} · Issued: {c.currentProperty.reduce((n,p)=>n+p.quantity,0)} · Still Needed: {needs.filter(n=>n.status!=='FULFILLED'&&n.status!=='CANCELLED').length} · {cadetReadiness(needs).status}</small></button>})}{!activeCadets.length&&<p className="empty-state">No active cadets found.</p>}</div></section>}
    {step===1&&cadet&&mode==='ISSUE'&&<section><h3>Choose Issue Type</h3><p>{cadet.fullName} · Recommended choices appear first; other bundles remain available.</p><div className="workflow-list">{[...state.bundles].sort((a,b)=>Number(recommendation.includes(b.versions.at(-1)!.displayName))-Number(recommendation.includes(a.versions.at(-1)!.displayName))).filter(b=>b.versions.at(-1)?.active).map(b=>{const v=b.versions.at(-1)!;return <button key={b.bundleId} onClick={()=>chooseBundle(b.bundleId)}><b>{v.displayName} <small>v{v.version}</small></b><small>{recommendation.includes(v.displayName)?'Recommended · ':''}{v.lines.length} configured lines</small></button>})}<button onClick={()=>{setBundleId('individual');setLines([]);setStep(2)}}><b>Individual Item</b><small>Search and add one or more inventory items</small></button></div></section>}
    {step===1&&cadet&&mode==='RETURN'&&<section><h3>Current Property</h3>{!lines.length?<p className="empty-state">No issued property recorded.</p>:<LineEditor lines={lines} setLines={setLines} state={state} returning/>}<button className="primary-button" disabled={!lines.some(l=>l.included)} onClick={()=>setStep(2)}>Configure return <ArrowRight/></button></section>}
    {step===2&&!review&&<section><h3>{mode==='ISSUE'?'Configure Items':'Return Quantities'}</h3>{mode==='ISSUE'&&bundleId==='individual'&&<><label className="workflow-search"><Search/><input aria-label="Search inventory" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, category, size, or NIIN…"/></label><div className="inventory-picker">{inventory.filter(i=>!lines.some(l=>l.itemId===i.entityId) && [i.name,i.detail?.category,i.detail?.size,i.detail?.niin].some(v=>v?.toLowerCase().includes(query.toLowerCase()))).map(i=><button key={i.entityId} onClick={()=>addIndividual(i.entityId)}><b>{i.name}</b><small>{i.detail?.size ?? 'No size'} · On hand {i.onHand}</small></button>)}</div></>}<LineEditor lines={lines} setLines={setLines} state={state}/><div className="sticky-workflow"><span>{mode==='ISSUE'?`${ready.length} ready · ${missing.length} missing`:`${lines.filter(l=>l.included).length} selected`}</span><button className="primary-button" disabled={mode==='ISSUE'?!ready.length&&!missing.length:!lines.some(l=>l.included)} onClick={()=>{setReview(true);setStep(3)}}>Review {mode==='ISSUE'?'Issue':'Return'}</button></div></section>}
    {review&&<section><h3>{mode==='ISSUE'?'ISSUE TO':'RETURN FROM'}</h3><div className="record-hero"><div><b>{cadet?.fullName}</b><p>{cadet?.nsLevel} · {cadet?.gender}</p></div></div>{selectedBundle&&<p><b>Bundle:</b> {selectedBundle.displayName} v{selectedBundle.version}</p>}<h4>{mode==='ISSUE'?'READY TO ISSUE':'RETURNING'}</h4><ReviewLines lines={mode==='ISSUE'?ready:lines.filter(l=>l.included)} state={state} returning={mode==='RETURN'}/>{mode==='ISSUE'&&missing.length>0&&<><h4>STILL NEEDED AFTER ISSUE</h4><ReviewLines lines={missing} state={state}/><p className="workflow-warning">Required items are missing. Confirming will issue available items and keep these requirements open.</p></>}<div className="sticky-workflow"><button onClick={()=>{setReview(false);setStep(2)}}><ArrowLeft/> Edit</button><button className="primary-button" disabled={busy} onClick={()=>void confirm()}>{busy?'COMMITTING…':`CONFIRM ${mode}`}</button></div></section>}
  </Shell>
}

function Shell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="drawer-backdrop" role="presentation"><aside className="demo-drawer supply-workflow" role="dialog" aria-modal="true" aria-labelledby="supply-title"><header><span className="drawer-icon"><PackagePlus/></span><div><p className="eyebrow">SIGNED SUPPLY TRANSACTION</p><h2 id="supply-title">{title}</h2></div><button aria-label="Close workflow" onClick={onClose}><X/></button></header>{children}</aside></div>}
function LineEditor({lines,setLines,state,returning=false}:{lines:DraftLine[];setLines:(v:DraftLine[])=>void;state:RepositoryState;returning?:boolean}){const update=(i:number,p:Partial<DraftLine>)=>setLines(lines.map((l,x)=>x===i?{...l,...p}:l));return <div className="line-editor">{lines.map((line,i)=>{const item=state.inventory.find(x=>x.entityId===line.itemId);return <article key={line.lineId}><label className="line-toggle"><input type="checkbox" checked={line.included} onChange={e=>update(i,{included:e.target.checked})}/><span><b>{line.label}</b><small>{line.required?'Required':'Optional'} · {returning?`Held ${state.cadets.flatMap(c=>c.currentProperty).find(p=>p.propertyId===line.propertyId)?.quantity ?? 0}`:`On hand ${item?.onHand ?? 0}`}</small></span></label>{line.size&&<label>Size<input aria-label={`${line.label} size`} value={line.size} onChange={e=>update(i,{size:e.target.value})}/></label>}<label>Qty<input aria-label={`${line.label} quantity`} type="number" min="1" max={returning?state.cadets.flatMap(c=>c.currentProperty).find(p=>p.propertyId===line.propertyId)?.quantity:100} value={line.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></label>{!item&&!returning&&<strong className="unavailable">NOT CONFIGURED · WILL REMAIN STILL NEEDED</strong>}{item&&item.onHand<line.quantity&&!returning&&<strong className="unavailable">UNAVAILABLE · WILL REMAIN STILL NEEDED</strong>}</article>})}</div>}
function ReviewLines({lines,state,returning=false}:{lines:DraftLine[];state:RepositoryState;returning?:boolean}){return <div className="review-lines">{lines.map(l=>{const item=state.inventory.find(i=>i.entityId===l.itemId);return <div key={l.lineId}><span><b>{l.label}</b><small>{l.size??'No size'} ×{l.quantity}</small></span>{returning&&<em>{item?.onHand??0} → {(item?.onHand??0)+l.quantity}</em>}</div>})}</div>}
