import { useMemo, useRef, useState } from 'react'
import { ArrowLeft, Check, PackagePlus, Search, X } from 'lucide-react'
import type { ArgusAppProjection, DistributedAppController } from '../distributed/appIntegration'
import type { BundleLineProjection, InventoryProjection } from '../distributed/types'
import { bundleSuggestions } from '../stage3/domain'

type Props = { mode:'ISSUE'|'RETURN'; projection:ArgusAppProjection; controller:DistributedAppController; selectedCadetId?:string; onClose:()=>void; onChanged:(projection:ArgusAppProjection)=>void }
type DraftLine = { lineId:string; itemId?:string; label:string; quantity:number; required:boolean; included:boolean; propertyId?:string }

const currentVersion = (bundle:ArgusAppProjection['bundles'][number]) => bundle.versions.find(version=>version.version===bundle.currentVersion)
const variantsFor = (inventory:InventoryProjection[], itemId?:string) => { const selected=inventory.find(item=>item.entityId===itemId); return selected ? inventory.filter(item=>item.name===selected.name) : [] }
const returnDraft = (cadet:ArgusAppProjection['cadets'][number]) => cadet.currentProperty.map(property=>({lineId:crypto.randomUUID(),itemId:property.itemId,label:property.label,quantity:property.quantity,required:false,included:false,propertyId:property.propertyId}))

export function SupplyWorkflow({mode,projection,controller,selectedCadetId,onClose,onChanged}:Props){
 const initialCadet=projection.cadets.find(cadet=>cadet.cadetId===selectedCadetId)
 const [cadetId,setCadetId]=useState(initialCadet?.cadetId??''),[step,setStep]=useState(initialCadet?1:0),[query,setQuery]=useState(''),[bundleId,setBundleId]=useState<string>(),[lines,setLines]=useState<DraftLine[]>(()=>mode==='RETURN'&&initialCadet?returnDraft(initialCadet):[]),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ArgusAppProjection>()
 const transactionId=useRef(`supply:${crypto.randomUUID()}`),eventId=useRef(`event:${crypto.randomUUID()}`)
 const cadet=projection.cadets.find(candidate=>candidate.cadetId===cadetId),bundle=projection.bundles.find(candidate=>candidate.bundleId===bundleId),version=bundle&&currentVersion(bundle)
 const candidates=useMemo(()=>projection.cadets.filter(candidate=>(mode==='RETURN'?candidate.currentProperty.length>0:candidate.status==='ACTIVE')&&candidate.fullName.toLowerCase().includes(query.toLowerCase())),[projection.cadets,mode,query])
 const ready=lines.filter(line=>line.included&&line.itemId&&(projection.inventory.find(item=>item.entityId===line.itemId)?.onHand??0)>=line.quantity)
 const missing=lines.filter(line=>line.required&&(!line.included||!line.itemId||(projection.inventory.find(item=>item.entityId===line.itemId)?.onHand??0)<line.quantity))
 const selectedReturns=lines.filter(line=>line.included)
 const chooseCadet=(id:string)=>{setCadetId(id);setStep(1);if(mode==='RETURN'){const selected=projection.cadets.find(candidate=>candidate.cadetId===id)!;setLines(returnDraft(selected))}}
 const chooseBundle=(id:string)=>{const selectedBundle=projection.bundles.find(candidate=>candidate.bundleId===id),selectedVersion=selectedBundle&&currentVersion(selectedBundle);setBundleId(id);setLines(selectedVersion?[...selectedVersion.lines].sort((a,b)=>a.order-b.order).map(line=>fromBundleLine(line,projection.inventory,cadet?.sizes??{})):[]);setStep(2)}
 const addItem=(item:InventoryProjection)=>setLines(current=>current.some(line=>line.itemId===item.entityId)?current:[...current,{lineId:crypto.randomUUID(),itemId:item.entityId,label:item.name,quantity:1,required:false,included:true}])
 const confirm=async()=>{if(busy)return;setBusy(true);setError('');try{const next=mode==='ISSUE'?await controller.issueTransaction({transactionId:transactionId.current,cadetId,lines:ready.map(line=>({lineId:line.lineId,itemId:line.itemId!,quantity:line.quantity})),missingLines:missing.map(line=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId);return{lineId:line.lineId,itemId:item?.entityId,label:line.label,variant:item?.variant,quantity:line.quantity,required:true as const}}),...(version?{bundleId:version.bundleId,bundleVersion:version.version}:{})},{eventId:eventId.current}):await controller.returnTransaction({transactionId:transactionId.current,cadetId,lines:selectedReturns.map(line=>({lineId:line.lineId,propertyId:line.propertyId!,quantity:line.quantity}))},{eventId:eventId.current});setResult(next);onChanged(next)}catch(reason){setError(reason instanceof Error?reason.message:'The transaction could not be completed.');setReview(false);setStep(2)}finally{setBusy(false)}}
 if(result)return <Shell title={`${mode==='ISSUE'?'Issue':'Return'} Complete`} close={onClose}><div className="workflow-success"><Check/><h3>{mode==='ISSUE'?'Issue':'Return'} Complete</h3><p>{result.sync.outbox?'Saved locally · Sync queued':'Synchronized'}</p><button className="primary-button" onClick={onClose}>Done</button></div></Shell>
 return <Shell title={mode==='ISSUE'?'Issue property':'Return property'} close={onClose}>
  <ol className="workflow-steps">{['Cadet',mode==='ISSUE'?'Type':'Property','Configure','Review'].map((label,index)=><li key={label} className={index<=step?'active':''}>{index+1}<span>{label}</span></li>)}</ol>
  {error&&<p className="workflow-error" role="alert">{error}</p>}
  {step===0&&<section><h3>Select Cadet</h3><SearchField value={query} change={setQuery} label="Search cadets"/><div className="workflow-list">{candidates.map(candidate=><button key={candidate.cadetId} onClick={()=>chooseCadet(candidate.cadetId)}><b>{candidate.fullName}</b><small>{candidate.nsLevel} · {candidate.gender} · {candidate.propertyCount} issued</small></button>)}{!candidates.length&&<p className="empty-state">{mode==='RETURN'?'No cadets with current property found.':'No active cadets found.'}</p>}</div></section>}
  {step===1&&cadet&&mode==='ISSUE'&&<section><CadetSummary cadet={cadet} change={()=>{setCadetId('');setStep(0)}}/><h3>Choose Issue Type</h3><div className="workflow-list">{[...projection.bundles].filter(item=>currentVersion(item)?.active).sort((a,b)=>Number(bundleSuggestions(cadet.gender).includes(currentVersion(b)!.displayName))-Number(bundleSuggestions(cadet.gender).includes(currentVersion(a)!.displayName))).map(item=>{const current=currentVersion(item)!;return <button key={item.bundleId} onClick={()=>chooseBundle(item.bundleId)}><b>{current.displayName} · v{current.version}</b><small>{bundleSuggestions(cadet.gender).includes(current.displayName)?'Recommended · ':''}{item.mapping.status.replaceAll('_',' ')}</small></button>})}<button onClick={()=>{setBundleId(undefined);setLines([]);setStep(2)}}><b>Individual Item</b><small>Add one or more authoritative inventory variants</small></button></div></section>}
  {step===1&&cadet&&mode==='RETURN'&&<section><CadetSummary cadet={cadet} change={()=>{setCadetId('');setStep(0)}}/><h3>Current Property</h3><LineEditor lines={lines} update={setLines} projection={projection} returning/><button className="primary-button" disabled={!selectedReturns.length} onClick={()=>setStep(2)}>Configure Return</button></section>}
  {step===2&&!review&&<section><CadetSummary cadet={cadet!}/><h3>{mode==='ISSUE'?'Configure Items':'Return Quantities'}</h3>{mode==='ISSUE'&&!version&&<InventoryPicker projection={projection} query={query} setQuery={setQuery} add={addItem} selected={lines}/>}<LineEditor lines={lines} update={setLines} projection={projection} returning={mode==='RETURN'}/><div className="sticky-workflow"><span>{mode==='ISSUE'?`${ready.length} ready · ${missing.length} still needed`:`${selectedReturns.length} selected`}</span><button className="primary-button" disabled={mode==='ISSUE'?!ready.length&&!missing.length:!selectedReturns.length} onClick={()=>{setReview(true);setStep(3)}}>Review {mode==='ISSUE'?'Issue':'Return'}</button></div></section>}
  {review&&<section><h3>{mode==='ISSUE'?'ISSUE TO':'RETURN FROM'}</h3><CadetSummary cadet={cadet!}/>{version&&<p><b>Bundle:</b> {version.displayName} v{version.version}</p>}<h4>{mode==='ISSUE'?'READY TO ISSUE':'RETURNING'}</h4><ReviewLines lines={mode==='ISSUE'?ready:selectedReturns} projection={projection} returning={mode==='RETURN'}/>{mode==='ISSUE'&&missing.length>0&&<><h4>STILL NEEDED AFTER ISSUE</h4><ReviewLines lines={missing} projection={projection}/><p className="workflow-warning">This is a partial issue. Only ready items will issue; required missing items will remain Still Needed.</p></>}<div className="sticky-workflow"><button onClick={()=>{setReview(false);setStep(2)}}><ArrowLeft/> Edit</button><button className="primary-button" disabled={busy} onClick={()=>void confirm()}>{busy?'COMMITTING…':`CONFIRM ${mode}`}</button></div></section>}
 </Shell>
}

function fromBundleLine(line:BundleLineProjection,inventory:InventoryProjection[],sizes:Record<string,string>):DraftLine{const mapped=inventory.find(item=>item.entityId===line.itemId);if(!mapped)return{lineId:line.lineId,label:line.displayLabel,quantity:line.defaultQuantity,required:line.required,included:line.required};const preferred=sizes[line.displayLabel]??sizes[mapped.name];const chosen=preferred?variantsFor(inventory,mapped.entityId).find(item=>item.variant===preferred)??mapped:mapped;return{lineId:line.lineId,itemId:chosen.entityId,label:line.displayLabel,quantity:line.defaultQuantity,required:line.required,included:line.required||chosen.onHand>0}}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="drawer-backdrop"><aside className="demo-drawer supply-workflow" role="dialog" aria-label={title}><header><span className="drawer-icon"><PackagePlus/></span><div><small>SIGNED SUPPLY TRANSACTION</small><h2>{title}</h2></div><button aria-label="Close workflow" onClick={close}><X/></button></header>{children}</aside></div>}
function SearchField({value,change,label}:{value:string;change:(value:string)=>void;label:string}){return <label className="workflow-search"><Search/><input value={value} onChange={event=>change(event.target.value)} aria-label={label} placeholder={`${label}…`}/>{value&&<button aria-label="Clear search" onClick={()=>change('')}><X/></button>}</label>}
function CadetSummary({cadet,change}:{cadet:ArgusAppProjection['cadets'][number];change?:()=>void}){return <div className="record-hero"><div><b>{cadet.fullName}</b><p>{cadet.nsLevel} · {cadet.gender} · {cadet.status}</p></div>{change&&<button onClick={change}>Change Cadet</button>}</div>}
function InventoryPicker({projection,query,setQuery,add,selected}:{projection:ArgusAppProjection;query:string;setQuery:(value:string)=>void;add:(item:InventoryProjection)=>void;selected:DraftLine[]}){const matches=projection.inventory.filter(item=>item.active&&!selected.some(line=>line.itemId===item.entityId)&&[item.name,item.category,item.variant,item.niin].some(value=>value.toLowerCase().includes(query.toLowerCase())));return <><SearchField value={query} change={setQuery} label="Search inventory"/><div className="inventory-picker">{matches.map(item=><button key={item.entityId} onClick={()=>add(item)}><b>{item.name}</b><small>{item.variant} · On hand {item.onHand}</small></button>)}{!matches.length&&<p className="empty-state">No inventory matches your search.</p>}</div></>}
function LineEditor({lines,update,projection,returning=false}:{lines:DraftLine[];update:(lines:DraftLine[])=>void;projection:ArgusAppProjection;returning?:boolean}){const patch=(index:number,changes:Partial<DraftLine>)=>update(lines.map((line,current)=>current===index?{...line,...changes}:line));return <div className="line-editor">{lines.map((line,index)=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId),variants=variantsFor(projection.inventory,line.itemId),property=projection.cadets.flatMap(cadet=>cadet.currentProperty).find(candidate=>candidate.propertyId===line.propertyId);return <article key={line.lineId}><label className="line-toggle"><input type="checkbox" checked={line.included} onChange={event=>patch(index,{included:event.target.checked})}/><span><b>{line.label}</b><small>{line.required?'Required':'Optional'} · {returning?`Held ${property?.quantity??0}`:item?`On hand ${item.onHand}`:'Inventory item not configured'}</small></span></label>{!returning&&variants.length>1&&<label>Variant<select aria-label={`${line.label} variant`} value={line.itemId} onChange={event=>patch(index,{itemId:event.target.value})}>{variants.map(option=><option key={option.entityId} value={option.entityId}>{option.variant} · {option.onHand} on hand</option>)}</select></label>}{item&&variants.length===1&&item.variant!=='No variant'&&<p>{item.variant}</p>}<label>Quantity<input aria-label={`${line.label} quantity`} type="number" min="1" max={returning?property?.quantity:100} value={line.quantity} onChange={event=>patch(index,{quantity:Number(event.target.value)})}/></label>{!item&&<strong className="unavailable">NOT CONFIGURED</strong>}{item&&!returning&&item.onHand<line.quantity&&<strong className="unavailable">UNAVAILABLE</strong>}</article>})}</div>}
function ReviewLines({lines,projection,returning=false}:{lines:DraftLine[];projection:ArgusAppProjection;returning?:boolean}){return <div className="review-lines">{lines.map(line=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId);return <div key={line.lineId}><span><b>{line.label}</b><small>{item?.variant??'Inventory item not configured'} ×{line.quantity}</small></span>{returning&&item&&<em>{item.onHand} → {item.onHand+line.quantity}</em>}</div>})}</div>}
