import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowLeft, Check, Minus, PackagePlus, Plus, Search, X } from 'lucide-react'
import type { ArgusAppProjection, DistributedAppController } from '../distributed/appIntegration'
import type { BundleLineProjection, InventoryProjection } from '../distributed/types'
import { bundleSuggestions } from '../stage3/domain'

type Props = { mode:'ISSUE'|'RETURN'; projection:ArgusAppProjection; controller:DistributedAppController; selectedCadetId?:string; onClose:()=>void; onChanged:(projection:ArgusAppProjection)=>void }
type DraftLine = { lineId:string; itemId?:string; label:string; quantity:string; required:boolean; included:boolean; propertyId?:string }

const currentVersion = (bundle:ArgusAppProjection['bundles'][number]) => bundle.versions.find(version=>version.version===bundle.currentVersion)
const variantsFor = (inventory:InventoryProjection[], itemId?:string) => { const selected=inventory.find(item=>item.entityId===itemId); return selected ? inventory.filter(item=>item.name===selected.name&&item.active) : [] }
const returnDraft = (cadet:ArgusAppProjection['cadets'][number]):DraftLine[] => cadet.currentProperty.map(property=>({lineId:crypto.randomUUID(),itemId:property.itemId,label:property.label,quantity:String(property.quantity),required:false,included:false,propertyId:property.propertyId}))
const quantityValue = (line:DraftLine) => Number(line.quantity)
const quantityError = (line:DraftLine,max:number) => {
 const value=quantityValue(line)
 if(!line.included)return ''
 if(!line.quantity.trim())return 'Enter a quantity.'
 if(!Number.isFinite(value)||!Number.isInteger(value))return 'Quantity must be a whole number.'
 if(value<1)return 'Quantity must be at least 1.'
 if(value>100)return 'Quantity cannot exceed 100.'
 if(value>max)return `Only ${max} available.`
 return ''
}

export function SupplyWorkflow({mode,projection,controller,selectedCadetId,onClose,onChanged}:Props){
 const initialCadet=projection.cadets.find(cadet=>cadet.cadetId===selectedCadetId)
 const [cadetId,setCadetId]=useState(initialCadet?.cadetId??''),[step,setStep]=useState(initialCadet?1:0)
 const [cadetQuery,setCadetQuery]=useState(''),[inventoryQuery,setInventoryQuery]=useState(''),[bundleId,setBundleId]=useState<string>()
 const [lines,setLines]=useState<DraftLine[]>(()=>mode==='RETURN'&&initialCadet?returnDraft(initialCadet):[]),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ArgusAppProjection>()
 const transactionId=useRef(`supply:${crypto.randomUUID()}`),eventId=useRef(`event:${crypto.randomUUID()}`)
 const cadet=projection.cadets.find(candidate=>candidate.cadetId===cadetId),bundle=projection.bundles.find(candidate=>candidate.bundleId===bundleId),version=bundle&&currentVersion(bundle)
 const candidates=useMemo(()=>projection.cadets.filter(candidate=>(mode==='RETURN'?candidate.currentProperty.length>0:candidate.status==='ACTIVE')&&candidate.fullName.toLowerCase().includes(cadetQuery.toLowerCase())),[projection.cadets,mode,cadetQuery])
 const propertyFor=(line:DraftLine)=>cadet?.currentProperty.find(property=>property.propertyId===line.propertyId)
 const maxFor=(line:DraftLine)=>mode==='RETURN'?(propertyFor(line)?.quantity??0):(projection.inventory.find(item=>item.entityId===line.itemId)?.onHand??0)
 const invalid=lines.filter(line=>quantityError(line,maxFor(line)))
 const ready=lines.filter(line=>line.included&&line.itemId&&!quantityError(line,maxFor(line)))
 const missing=lines.filter(line=>line.required&&(!line.included||!line.itemId||Boolean(quantityError(line,maxFor(line)))))
 const selectedReturns=lines.filter(line=>line.included&&!quantityError(line,maxFor(line)))
 const chooseCadet=(id:string)=>{const selected=projection.cadets.find(candidate=>candidate.cadetId===id);setCadetId(id);setBundleId(undefined);setInventoryQuery('');setLines(mode==='RETURN'&&selected?returnDraft(selected):[]);setReview(false);setError('');setStep(1)}
 const changeCadet=()=>{setCadetId('');setBundleId(undefined);setLines([]);setCadetQuery('');setInventoryQuery('');setReview(false);setError('');setStep(0)}
 const chooseBundle=(id:string)=>{const selectedBundle=projection.bundles.find(candidate=>candidate.bundleId===id),selectedVersion=selectedBundle&&currentVersion(selectedBundle);setBundleId(id);setInventoryQuery('');setLines(selectedVersion?[...selectedVersion.lines].sort((a,b)=>a.order-b.order).map(line=>fromBundleLine(line,projection.inventory,cadet?.sizes??{})):[]);setReview(false);setError('');setStep(2)}
 const chooseIndividual=()=>{setBundleId(undefined);setLines([]);setInventoryQuery('');setReview(false);setError('');setStep(2)}
 const addItem=(item:InventoryProjection)=>setLines(current=>current.some(line=>line.itemId===item.entityId)?current:[...current,{lineId:crypto.randomUUID(),itemId:item.entityId,label:item.name,quantity:'1',required:false,included:true}])
 const canReview=mode==='ISSUE'?(ready.length>0||missing.length>0)&&invalid.every(line=>line.required):selectedReturns.length>0&&invalid.length===0
 const confirm=async()=>{if(busy||!canReview)return;setBusy(true);setError('');try{const next=mode==='ISSUE'?await controller.issueTransaction({transactionId:transactionId.current,cadetId,lines:ready.map(line=>({lineId:line.lineId,itemId:line.itemId!,quantity:quantityValue(line)})),missingLines:missing.map(line=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId);return{lineId:line.lineId,itemId:item?.entityId,label:line.label,variant:item?.variant,quantity:Math.min(100,Math.max(1,Number.isInteger(quantityValue(line))?quantityValue(line):1)),required:true as const}}),...(version?{bundleId:version.bundleId,bundleVersion:version.version}:{})},{eventId:eventId.current}):await controller.returnTransaction({transactionId:transactionId.current,cadetId,lines:selectedReturns.map(line=>({lineId:line.lineId,propertyId:line.propertyId!,quantity:quantityValue(line)}))},{eventId:eventId.current});setResult(next);onChanged(next)}catch(reason){setError(friendlyError(reason));setReview(false);setStep(2)}finally{setBusy(false)}}
 if(result)return <Shell title={`${mode==='ISSUE'?'Issue':'Return'} Complete`} close={onClose}><div className="workflow-success" role="status"><Check/><p className="operational-label">Transaction complete</p><h3>{mode==='ISSUE'?'Issue':'Return'} Complete</h3><strong>{cadet?.fullName}</strong><p>{mode==='ISSUE'?`${ready.reduce((sum,line)=>sum+quantityValue(line),0)} items issued${missing.length?` · ${missing.length} added to Still Needed`:''}`:`${selectedReturns.reduce((sum,line)=>sum+quantityValue(line),0)} items returned`}</p><span className="sync-note">Saved locally · {result.sync.outbox?`${result.sync.outbox} change${result.sync.outbox===1?'':'s'} queued`:'development sync provider'}</span><button className="primary-button" onClick={onClose}>Done</button></div></Shell>
 return <Shell title={mode==='ISSUE'?'Issue property':'Return property'} close={onClose}>
  <ol className="workflow-steps" aria-label="Transaction progress">{['Cadet',mode==='ISSUE'?'Issue type':'Property','Configure','Review'].map((label,index)=><li key={label} className={index===step?'active':index<step?'complete':''} aria-current={index===step?'step':undefined}><span className="step-number">{index<step?<Check/>:index+1}</span><span>{label}</span></li>)}</ol>
  {error&&<p className="workflow-error" role="alert"><AlertTriangle/>{error}</p>}
  {step===0&&<section aria-labelledby="cadet-heading"><div className="workflow-heading"><p className="operational-label">Step 1</p><h3 id="cadet-heading">Select a cadet</h3><p>Choose the personnel record for this {mode.toLowerCase()} transaction.</p></div><SearchField value={cadetQuery} change={setCadetQuery} label="Search cadets"/><div className="workflow-list cadet-options">{candidates.map(candidate=><button key={candidate.cadetId} onClick={()=>chooseCadet(candidate.cadetId)}><span className="large-avatar">{candidate.fullName.split(/\s+/).map(part=>part[0]).join('').slice(0,2)}</span><span><b>{candidate.fullName}</b><small>{candidate.nsLevel} · {candidate.status.toLowerCase()}</small><em>{candidate.propertyCount} held · {candidate.stillNeededCount} still needed</em></span><span className="select-label">Select</span></button>)}{!candidates.length&&<p className="empty-state"><strong>No matching cadets</strong><span>{mode==='RETURN'?'Only cadets holding property are shown.':'Try another name or clear the search.'}</span></p>}</div></section>}
  {step===1&&cadet&&mode==='ISSUE'&&<section><CadetSummary cadet={cadet} change={changeCadet}/><div className="workflow-heading"><p className="operational-label">Step 2</p><h3>Choose issue type</h3><p>Use a mapped bundle or select individual inventory.</p></div><IssueTypes projection={projection} cadet={cadet} chooseBundle={chooseBundle} chooseIndividual={chooseIndividual}/></section>}
  {step===1&&cadet&&mode==='RETURN'&&<section><CadetSummary cadet={cadet} change={changeCadet}/><div className="workflow-heading"><p className="operational-label">Current property</p><h3>Select property to return</h3><p>Only items currently held by this cadet are available.</p></div><LineEditor lines={lines} update={setLines} projection={projection} cadet={cadet} returning/><button className="primary-button wide-action" disabled={!lines.some(line=>line.included)} onClick={()=>setStep(2)}>Configure Return</button></section>}
  {step===2&&!review&&<section><CadetSummary cadet={cadet!}/><div className="workflow-heading"><p className="operational-label">Step 3</p><h3>{mode==='ISSUE'?'Configure issue':'Confirm return quantities'}</h3><p>{mode==='ISSUE'?'Required shortages will be recorded as Still Needed.':'A return cannot exceed the quantity held.'}</p></div>{mode==='ISSUE'&&!version&&<InventoryPicker projection={projection} query={inventoryQuery} setQuery={setInventoryQuery} add={addItem} selected={lines}/>}<LineEditor lines={lines} update={setLines} projection={projection} cadet={cadet!} returning={mode==='RETURN'}/>{mode==='ISSUE'&&missing.length>0&&<div className="workflow-warning"><AlertTriangle/><span><strong>Partial issue</strong> {missing.length} required item{missing.length===1?' is':'s are'} unavailable and will remain Still Needed.</span></div>}<div className="sticky-workflow"><span>{mode==='ISSUE'?<><b>{ready.length} ready</b><small>{missing.length} still needed</small></>:<><b>{selectedReturns.length} selected</b><small>{invalid.length?'Correct invalid quantities':'Ready for review'}</small></>}</span><button className="primary-button" disabled={!canReview} onClick={()=>{setReview(true);setStep(3)}}>Review {mode==='ISSUE'?'Issue':'Return'}</button></div></section>}
  {review&&<section className="transaction-review"><p className="operational-label">{mode==='ISSUE'?'Issue to':'Return from'}</p><CadetSummary cadet={cadet!}/>{version&&<div className="bundle-summary"><span>Bundle</span><strong>{version.displayName}</strong><small>Version {version.version}</small></div>}<ReviewGroup title={mode==='ISSUE'?'Ready to issue':'Returning'} lines={mode==='ISSUE'?ready:selectedReturns} projection={projection} returning={mode==='RETURN'}/>{mode==='ISSUE'&&missing.length>0&&<><ReviewGroup title="Still needed after issue" lines={missing} projection={projection}/><p className="workflow-warning"><AlertTriangle/>This partial issue will save required shortages to the cadet’s Still Needed record.</p></>}<div className="review-totals"><b>{mode==='ISSUE'?ready.length:selectedReturns.length} item{(mode==='ISSUE'?ready.length:selectedReturns.length)===1?'':'s'} ready</b>{mode==='ISSUE'&&<span>{missing.length} still needed</span>}</div><div className="sticky-workflow"><button className="secondary-button" onClick={()=>{setReview(false);setStep(2)}}><ArrowLeft/> Edit</button><button className="primary-button" disabled={busy} onClick={()=>void confirm()}>{busy?'Saving…':`Confirm ${mode==='ISSUE'?'Issue':'Return'}`}</button></div></section>}
 </Shell>
}

function friendlyError(reason:unknown){const message=reason instanceof Error?reason.message:'';if(/inventory|on hand|available/i.test(message))return 'Inventory changed or is insufficient. Review the highlighted items and try again.';if(/permission|authoriz/i.test(message))return 'Your account is not authorized to complete this transaction.';if(/property|held|return/i.test(message))return 'The cadet’s property changed. Review the return quantities and try again.';if(/conflict/i.test(message))return 'A record conflict requires attention before this transaction can continue.';return 'The transaction could not be saved. Your draft is preserved; review it and try again.'}
function fromBundleLine(line:BundleLineProjection,inventory:InventoryProjection[],sizes:Record<string,string>):DraftLine{const mapped=inventory.find(item=>item.entityId===line.itemId);if(!mapped)return{lineId:line.lineId,label:line.displayLabel,quantity:String(line.defaultQuantity),required:line.required,included:line.required};const preferred=sizes[line.displayLabel]??sizes[mapped.name];const chosen=preferred?variantsFor(inventory,mapped.entityId).find(item=>item.variant===preferred)??mapped:mapped;return{lineId:line.lineId,itemId:chosen.entityId,label:line.displayLabel,quantity:String(line.defaultQuantity),required:line.required,included:line.required||chosen.onHand>0}}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="drawer-backdrop"><aside className="demo-drawer supply-workflow" role="dialog" aria-modal="true" aria-label={title}><header><span className="drawer-icon"><PackagePlus/></span><div><small>Signed supply transaction</small><h2>{title}</h2></div><button className="icon-button" aria-label="Close workflow" onClick={close}><X/></button></header>{children}</aside></div>}
function SearchField({value,change,label}:{value:string;change:(value:string)=>void;label:string}){return <label className="workflow-search"><Search/><span className="sr-only">{label}</span><input value={value} onChange={event=>change(event.target.value)} aria-label={label} placeholder={`${label}…`}/>{value&&<button type="button" aria-label={`Clear ${label.toLowerCase()}`} onClick={()=>change('')}><X/></button>}</label>}
function CadetSummary({cadet,change}:{cadet:ArgusAppProjection['cadets'][number];change?:()=>void}){return <div className="record-hero"><div><small>Cadet record</small><b>{cadet.fullName}</b><p>{cadet.nsLevel} · {cadet.status.toLowerCase()} · {cadet.propertyCount} items held</p></div>{change&&<button className="secondary-button" onClick={change}>Change Cadet</button>}</div>}
function IssueTypes({projection,cadet,chooseBundle,chooseIndividual}:{projection:ArgusAppProjection;cadet:ArgusAppProjection['cadets'][number];chooseBundle:(id:string)=>void;chooseIndividual:()=>void}){const bundles=projection.bundles.filter(item=>currentVersion(item)?.active),suggestions=bundleSuggestions(cadet.gender);const card=(item:typeof bundles[number])=>{const current=currentVersion(item)!,recommended=suggestions.includes(current.displayName),unsafe=item.mapping.status!=='FULLY_MAPPED';return <button className="issue-type-card" key={item.bundleId} onClick={()=>chooseBundle(item.bundleId)}><span><b>{current.displayName}</b><small>Bundle version {current.version} · {item.mapping.total} items</small></span>{recommended&&<em className="status-badge recommended">Recommended</em>}<span className={`status-badge ${unsafe?'warning':'success'}`}>{item.mapping.status.replaceAll('_',' ').toLowerCase()} · {item.mapping.mapped}/{item.mapping.total}</span>{unsafe&&<span className="mapping-warning"><AlertTriangle/>Review unmapped items before issue</span>}</button>};return <div className="issue-types">{bundles.some(item=>suggestions.includes(currentVersion(item)!.displayName))&&<><h4>Recommended bundles</h4>{bundles.filter(item=>suggestions.includes(currentVersion(item)!.displayName)).map(card)}</>}<h4>Other options</h4>{bundles.filter(item=>!suggestions.includes(currentVersion(item)!.displayName)).map(card)}<button className="issue-type-card individual" onClick={chooseIndividual}><span><b>Individual Issue</b><small>Choose one or more authoritative inventory variants</small></span><span className="select-label">Select items</span></button></div>}
function InventoryPicker({projection,query,setQuery,add,selected}:{projection:ArgusAppProjection;query:string;setQuery:(value:string)=>void;add:(item:InventoryProjection)=>void;selected:DraftLine[]}){const matches=projection.inventory.filter(item=>item.active&&!selected.some(line=>line.itemId===item.entityId)&&[item.name,item.category,item.variant,item.niin].some(value=>value.toLowerCase().includes(query.toLowerCase())));return <div className="picker-section"><SearchField value={query} change={setQuery} label="Search inventory"/><div className="inventory-picker">{matches.map(item=><button key={item.entityId} onClick={()=>add(item)}><span><b>{item.name}</b><small>{item.category} · {item.variant}</small></span><span><strong>{item.onHand}</strong><small>on hand</small></span><span className="select-label">Add</span></button>)}{!matches.length&&<p className="empty-state"><strong>No inventory matches</strong><span>Clear the search or choose another term.</span></p>}</div></div>}
function QuantityControl({line,max,patch}:{line:DraftLine;max:number;patch:(changes:Partial<DraftLine>)=>void}){const value=quantityValue(line),error=quantityError(line,max),set=(next:number)=>patch({quantity:String(Math.min(Math.min(100,max),Math.max(1,next))) });return <div className="quantity-field"><span>Quantity</span><div className="quantity-control"><button type="button" aria-label={`Decrease ${line.label} quantity`} disabled={!line.included||value<=1||!Number.isFinite(value)} onClick={()=>set(value-1)}><Minus/></button><input aria-label={`${line.label} quantity`} inputMode="numeric" value={line.quantity} disabled={!line.included} onChange={event=>patch({quantity:event.target.value})} aria-invalid={Boolean(error)} aria-describedby={error?`${line.lineId}-error`:undefined}/><button type="button" aria-label={`Increase ${line.label} quantity`} disabled={!line.included||value>=Math.min(100,max)||!Number.isFinite(value)} onClick={()=>set(value+1)}><Plus/></button></div>{error&&<small id={`${line.lineId}-error`} className="line-error" role="alert">{error}</small>}</div>}
function LineEditor({lines,update,projection,cadet,returning=false}:{lines:DraftLine[];update:(lines:DraftLine[])=>void;projection:ArgusAppProjection;cadet:ArgusAppProjection['cadets'][number];returning?:boolean}){const patch=(index:number,changes:Partial<DraftLine>)=>update(lines.map((line,current)=>current===index?{...line,...changes}:line));return <div className="line-editor">{lines.map((line,index)=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId),variants=variantsFor(projection.inventory,line.itemId),property=cadet.currentProperty.find(candidate=>candidate.propertyId===line.propertyId),max=returning?property?.quantity??0:item?.onHand??0,unavailable=!returning&&(!item||item.onHand<quantityValue(line));return <article key={line.lineId} className={`${line.included?'included':'excluded'} ${unavailable?'line-unavailable':''}`}><label className="line-toggle"><input type="checkbox" checked={line.included} onChange={event=>patch(index,{included:event.target.checked})}/><span><b>{line.label}</b><small>{line.required?'Required item':'Optional item'} · {returning?`Held: ${property?.quantity??0}`:item?`On hand: ${item.onHand}`:'No inventory mapping'}</small></span><strong className={`status-badge ${unavailable?'danger':line.included?'success':''}`}>{unavailable?'Unavailable':line.included?'Included':'Excluded'}</strong></label><div className="line-details">{!returning&&variants.length>1&&<label><span>Variant / size</span><select aria-label={`${line.label} variant`} value={line.itemId} onChange={event=>patch(index,{itemId:event.target.value})}>{variants.map(option=><option key={option.entityId} value={option.entityId}>{option.variant} · {option.onHand} on hand</option>)}</select></label>}{item&&variants.length===1&&<div><span>Variant / size</span><b>{item.variant}</b></div>}<QuantityControl line={line} max={max} patch={changes=>patch(index,changes)}/></div>{unavailable&&<p className="availability-message"><AlertTriangle/>Cannot issue now{line.required?' — this required item will be Still Needed.':'.'}</p>}</article>})}{!lines.length&&<p className="empty-state"><strong>No items selected</strong><span>Search inventory above and add an item.</span></p>}</div>}
function ReviewGroup({title,lines,projection,returning=false}:{title:string;lines:DraftLine[];projection:ArgusAppProjection;returning?:boolean}){return <div className="review-group"><h4>{title}<span>{lines.length}</span></h4><div className="review-lines">{lines.map(line=>{const item=projection.inventory.find(candidate=>candidate.entityId===line.itemId);return <div key={line.lineId}><span><b>{line.label}</b><small>{item?.variant??'Inventory item not configured'} · Quantity {line.quantity}</small></span>{returning&&item&&<em aria-label={`Stock changes from ${item.onHand} to ${item.onHand+quantityValue(line)}`}>{item.onHand} → {item.onHand+quantityValue(line)}</em>}</div>})}</div></div>}
