import { useEffect, useState } from 'react'
import { Activity, Archive, Boxes, ClipboardCheck, History, LayoutGrid, PackagePlus, Search, Settings, Users, X } from 'lucide-react'
import { DistributedAppController, type ArgusAppProjection } from './distributed/appIntegration'
import type { InventoryProjection } from './distributed/types'
import { LocalSettingsStorage, type SettingsStorage, type UserSettings } from './settings'
import { resolveBlockchainMode } from './blockchain/config'

export type Tab = 'count'|'inventory'|'cadets'|'activity'|'more'
const nav: Array<{ id: Tab; label: string; icon: typeof Activity }> = [{ id:'count',label:'Physical Count',icon:ClipboardCheck },{ id:'inventory',label:'Inventory',icon:Boxes },{ id:'cadets',label:'Cadets',icon:Users },{ id:'activity',label:'Activity',icon:History },{ id:'more',label:'More',icon:LayoutGrid }]
const initials = (name: string) => name.split(/\s+/).map(part => part[0]).join('').slice(0,2).toUpperCase()
const eventLabel = (type: string) => ({ CADET_CREATED:'Cadet Created',CADET_UPDATED:'Cadet Updated',BUNDLE_UPDATED:'Bundle Updated',STILL_NEEDED_ADDED:'Still Needed Added',INVENTORY_COUNT_SUBMITTED:'Count Submitted',INVENTORY_ITEM_CREATED:'Inventory Item Created' }[type] ?? type.replaceAll('_',' ').toLowerCase())

type Props = { controller?: DistributedAppController; settingsStorage?: SettingsStorage }
export default function App({ controller: supplied, settingsStorage: suppliedSettings }: Props) {
  const [controller] = useState(() => supplied ?? new DistributedAppController())
  const [settingsStorage] = useState(() => suppliedSettings ?? new LocalSettingsStorage())
  const [preferences,setPreferences] = useState<UserSettings>(() => settingsStorage.load())
  const [projection,setProjection] = useState<ArgusAppProjection>()
  const [tab,setTab] = useState<Tab>(preferences.defaultSection)
  const [selectedItemId,setSelectedItemId] = useState('')
  const [selectedCadetId,setSelectedCadetId] = useState<string>()
  const [count,setCount] = useState(0), [query,setQuery] = useState(''), [cadetQuery,setCadetQuery] = useState('')
  const [settingsOpen,setSettingsOpen] = useState(false), [addOpen,setAddOpen] = useState(false), [notice,setNotice] = useState('')
  useEffect(() => { let active=true; controller.initialize().then(value => { if (!active) return; setProjection(value); const first=value.inventory[0]; if(first){setSelectedItemId(first.entityId);setCount(first.onHand)} }).catch(error => setNotice(error instanceof Error?error.message:'Local data could not be loaded.')); return()=>{active=false} },[controller])
  useEffect(() => { settingsStorage.save(preferences); document.documentElement.dataset.theme=preferences.theme; document.documentElement.dataset.density=preferences.density; document.documentElement.dataset.motion=preferences.motion; document.documentElement.dataset.textSize=preferences.textSize },[preferences,settingsStorage])
  const command = async (operation:()=>Promise<ArgusAppProjection>, success:string) => { try { setProjection(await operation()); setNotice(success) } catch(error) { setNotice(error instanceof Error?error.message:'The operation could not be completed.') } }
  if (!projection) return <main className="loading-state" aria-live="polite"><strong>Loading A.R.G.U.S. local data…</strong>{notice&&<p role="alert">{notice}</p>}</main>
  const selected=projection.inventory.find(item=>item.entityId===selectedItemId) ?? projection.inventory[0]
  const cadet=projection.cadets.find(item=>item.cadetId===selectedCadetId)
  const inventory=projection.inventory.filter(item=>[item.name,item.category,item.variant,item.niin].some(value=>value.toLowerCase().includes(query.toLowerCase())))
  const selectItem=(item:InventoryProjection)=>{setSelectedItemId(item.entityId);setCount(item.onHand)}
  return <div className="app-shell">
    <aside className="sidebar"><Brand/><nav aria-label="Primary navigation">{nav.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={()=>setTab(id)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="system-card"><strong>Development identity</strong><p>Prototype · local only</p></div><div className="profile"><span className="avatar">SO</span><span><strong>Development User</strong><small>Supply Officer</small></span></div></aside>
    <main className="main-stage"><div className={`environment-banner ${resolveBlockchainMode(import.meta.env.VITE_ARGUS_BLOCKCHAIN_MODE)}`}><strong>DEVELOPMENT</strong><span>No production transactions</span></div><header className="topbar"><div><p className="eyebrow">A.R.G.U.S.</p><h1>{nav.find(item=>item.id===tab)?.label}</h1></div><div className="top-actions"><span className="sync">{projection.sync.openConflicts?'CONFLICT · ACTION REQUIRED':projection.sync.outbox?`${projection.sync.outbox} CHANGES QUEUED`:'SYNCHRONIZED'}</span><button aria-label="Settings" className="icon-button" onClick={()=>setSettingsOpen(true)}><Settings/></button></div></header>
    {notice&&<div className="app-notice" role="status">{notice}</div>}
    {tab==='count'&&<section className="content count-page"><h2>Count with confidence.</h2><p>Draft state is local to this screen. Official inventory changes only on submission.</p><SearchBox label="Search inventory" value={query} setValue={setQuery}/><div className="panel-rows">{inventory.map(item=><button key={item.entityId} onClick={()=>selectItem(item)}><strong>{item.name}</strong><small>{item.variant} · {item.onHand} on hand</small></button>)}</div>{selected&&<div className="count-card"><h3>{selected.name} · {selected.variant}</h3><div className="count-display"><strong>{count}</strong></div><button onClick={()=>setCount(Math.max(0,count-selected.countIncrement))}>Subtract {selected.countIncrement}</button><button onClick={()=>setCount(count+selected.countIncrement)}>Add {selected.countIncrement}</button><button className="primary-button" onClick={()=>void command(()=>controller.submitCount(selected.entityId,count,'ui-count-session'),'Physical count submitted.')}>Submit count</button></div>}</section>}
    {tab==='inventory'&&<section className="content"><div className="page-intro"><div><h2>Every asset, accounted for.</h2></div><button className="gold-button" onClick={()=>setAddOpen(true)}><PackagePlus/>Add item</button></div><SearchBox label="Search inventory table" value={query} setValue={setQuery}/><div className="inventory-list">{inventory.map(item=><button className="inventory-row" key={item.entityId} onClick={()=>{selectItem(item);setTab('count')}}><span><strong>{item.name}</strong><small>{item.category} · {item.niin}</small></span><span>{item.variant}</span><b>{item.onHand} on hand</b><em className={item.onHand<= (item.reorderAt??-1)?'attention':'ready'}>{item.active?'ACTIVE':'INACTIVE'}</em></button>)}</div></section>}
    {tab==='cadets'&&<section className="content"><h2>Cadet property records.</h2><SearchBox label="Search cadets" value={cadetQuery} setValue={setCadetQuery}/><div className="cadet-grid">{projection.cadets.filter(c=>c.fullName.toLowerCase().includes(cadetQuery.toLowerCase())).map(c=><button className="cadet-card" key={c.cadetId} onClick={()=>setSelectedCadetId(c.cadetId)}><span className="large-avatar">{initials(c.fullName)}</span><span><strong>{c.fullName}</strong><small>{c.nsLevel} · {c.gender} · {c.status}</small></span><div><b>{c.propertyCount}</b><small>Current property</small></div><em className={c.readiness.status==='READY'?'ready':'attention'}>{c.readiness.status} · {c.stillNeededCount} needed</em></button>)}</div>{cadet&&<CadetDetail cadet={cadet} needs={projection.stillNeeded.filter(item=>item.cadetId===cadet.cadetId)} onClose={()=>setSelectedCadetId(undefined)}/>}</section>}
    {tab==='activity'&&<section className="content"><h2>Nothing changes silently.</h2><div className="timeline">{projection.events.map(record=><div className="event" key={record.event.eventId}><div><strong>{eventLabel(record.event.eventType)}</strong><p>{record.event.entityId}</p><small>Private sync: {record.syncStatus} · BSV audit: {record.auditStatus}</small></div><time>{new Date(record.event.timestamp).toLocaleString()}</time></div>)}{!projection.events.length&&<p>No activity yet.</p>}</div></section>}
    {tab==='more'&&<section className="content"><h2>Bundles & Still Needed</h2><h3>Bundles</h3><div className="panel-rows">{projection.bundles.map(bundle=>{const current=bundle.versions.find(v=>v.version===bundle.currentVersion)!;return <details key={bundle.bundleId}><summary><strong>{current.displayName}</strong> · v{bundle.currentVersion} · {current.active?'ACTIVE':'INACTIVE'} · {bundle.mapping.mapped}/{bundle.mapping.total} lines mapped</summary><p>{current.lines.filter(line=>line.required).length} required · {current.lines.filter(line=>!line.required).length} optional · {current.genderApplicability}</p><ul>{current.lines.map(line=><li key={line.lineId}>{line.displayLabel}: {line.itemId?'Mapped':'Inventory item not configured'}</li>)}</ul><h4>Version history</h4>{[...bundle.versions].reverse().map(v=><p key={v.version}>v{v.version}{v.version===bundle.currentVersion?' · CURRENT':''} · {new Date(v.createdAt).toLocaleDateString()} · {v.actorPublicIdentity}</p>)}</details>})}</div><h3>Still Needed</h3>{projection.stillNeeded.map(need=><div className="needed-row" key={need.requirementId}><strong>{projection.cadets.find(c=>c.cadetId===need.cadetId)?.fullName??'Missing cadet'}</strong><span>{need.displayLabel} · {need.quantityNeeded-need.quantityFulfilled} remaining</span><em>{need.availability.configured?(need.availability.available?'Available':'Awaiting stock'):'Inventory item not configured'}</em></div>)}</section>}
    </main>
    {settingsOpen&&<SettingsPanel value={preferences} report={projection.integrity} onChange={setPreferences} onClose={()=>setSettingsOpen(false)}/>} {addOpen&&<AddItem onClose={()=>setAddOpen(false)} onSave={input=>{setAddOpen(false);void command(()=>controller.createInventoryItem(input),`${input.name} was added.`)}}/>}
  </div>
}
function Brand(){return <div className="brand"><Archive/><span><strong>A.R.G.U.S.</strong><small>ASSET READINESS</small></span></div>}
function SearchBox({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <div className="inline-search"><Search/><input aria-label={label} value={value} onChange={e=>setValue(e.target.value)}/></div>}
function CadetDetail({cadet,needs,onClose}:{cadet:ArgusAppProjection['cadets'][number];needs:ArgusAppProjection['stillNeeded'];onClose:()=>void}){return <aside className="demo-drawer" role="dialog" aria-label="Cadet detail"><button aria-label="Close panel" onClick={onClose}><X/></button><h2>{cadet.fullName}</h2><p>{cadet.nsLevel} · {cadet.gender} · {cadet.status}</p>{cadet.profileNeedsReview&&<p className="attention">Profile needs review: gender was unavailable during migration.</p>}<h3>Current Property ({cadet.propertyCount})</h3>{cadet.currentProperty.length?cadet.currentProperty.map(item=><p key={`${item.itemId}-${item.issuedAt}`}>{item.label} · {item.quantity}</p>):<p>No current property.</p>}<h3>Still Needed ({needs.length})</h3>{needs.map(item=><p key={item.requirementId}>{item.displayLabel} · {item.status}</p>)}<strong>Readiness: {cadet.readiness.status}</strong><button disabled title="Coming Later in Stage 3B">Issue · Coming Later</button><button disabled title="Coming Later in Stage 3B">Return · Coming Later</button></aside>}
function SettingsPanel({value,report,onChange,onClose}:{value:UserSettings;report:ArgusAppProjection['integrity'];onChange:(v:UserSettings)=>void;onClose:()=>void}){const select=<K extends keyof UserSettings>(key:K,next:UserSettings[K])=>onChange({...value,[key]:next});return <aside className="demo-drawer" role="dialog" aria-label="Settings"><button aria-label="Close settings" onClick={onClose}><X/></button><h2>Settings</h2><h3>Appearance</h3><label>Theme<select aria-label="Appearance" value={value.theme} onChange={e=>select('theme',e.target.value as UserSettings['theme'])}><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Density<select aria-label="Density" value={value.density} onChange={e=>select('density',e.target.value as UserSettings['density'])}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Motion<select aria-label="Motion" value={value.motion} onChange={e=>select('motion',e.target.value as UserSettings['motion'])}><option value="full">Full</option><option value="reduced">Reduced</option></select></label><label>Text size<select aria-label="Text size" value={value.textSize} onChange={e=>select('textSize',e.target.value as UserSettings['textSize'])}><option value="standard">Standard</option><option value="large">Large</option></select></label><label>Default section<select aria-label="Default section" value={value.defaultSection} onChange={e=>select('defaultSection',e.target.value as Tab)}>{nav.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><h3>Advanced / Diagnostics</h3><strong>DATA INTEGRITY · {report.healthy?'Healthy':'Action required'}</strong><p>{report.orphanReferences} orphan references · {report.projectionErrors} open projection errors · {report.migrationWarnings} migration warnings</p><h3>Help</h3><p>A.R.G.U.S. version {__APP_VERSION__}</p><button disabled>Replay Tutorial · Coming Later</button><p>Basic help · Coming Later</p></aside>}
function AddItem({onClose,onSave}:{onClose:()=>void;onSave:(v:Omit<InventoryProjection,'entityId'|'version'|'appliedEventIds'|'issued'>)=>void}){const [name,setName]=useState(''),[category,setCategory]=useState(''),[variant,setVariant]=useState('No variant'),[niin,setNiin]=useState('Not assigned'),[onHand,setOnHand]=useState(0);return <form className="modal" aria-label="Add inventory item" onSubmit={e=>{e.preventDefault();onSave({name,category,variant,niin,onHand,countIncrement:1,active:true})}}><h2>Add a new item</h2><label>Item name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Category<input required value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Size or variant<input value={variant} onChange={e=>setVariant(e.target.value)}/></label><label>CDMIS NIIN<input value={niin} onChange={e=>setNiin(e.target.value)}/></label><label>Initial on hand<input type="number" min="0" value={onHand} onChange={e=>setOnHand(Number(e.target.value))}/></label><button type="button" onClick={onClose}>Cancel</button><button type="submit">Add item</button></form>}
