import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import App from './App'
import { DistributedAppController } from './distributed/appIntegration'
import { MemoryRepository } from './storage/repository'
import { DEFAULT_SETTINGS, LocalSettingsStorage, SETTINGS_KEY } from './settings'

const storage = () => { const values=new Map<string,string>(); return { getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>void values.set(key,value), values } }
async function setup(){const controller=new DistributedAppController(new MemoryRepository());await controller.initialize(storage());return controller}

describe('authoritative application UI',()=>{
  it('shows hydration before repository projections',()=>{render(<App controller={new DistributedAppController(new MemoryRepository())}/>);expect(screen.getByText('Loading A.R.G.U.S. local data…')).toBeInTheDocument()})
  it('renders repository cadets and switches selected opaque records',async()=>{const controller=await setup();await controller.createCadet({fullName:'Cadet Alpha',gender:'Female',nsLevel:'NS1',status:'ACTIVE'});await controller.createCadet({fullName:'Cadet Bravo',gender:'Male',nsLevel:'NS2',status:'ACTIVE'});render(<App controller={controller}/>);fireEvent.click(await screen.findByRole('button',{name:/cadets/i}));fireEvent.click(await screen.findByRole('button',{name:/cadet alpha/i}));expect(screen.getByRole('dialog',{name:'Cadet detail'})).toHaveTextContent('Cadet Alpha');fireEvent.click(screen.getByLabelText('Close panel'));fireEvent.click(screen.getByRole('button',{name:/cadet bravo/i}));expect(screen.getByRole('dialog',{name:'Cadet detail'})).toHaveTextContent('Cadet Bravo')})
  it('renders bundle projections, mapping status and immutable version history',async()=>{const controller=await setup();const before=(await controller.project()).bundles[0];const current=before.versions[0];await controller.updateBundle(before.bundleId,{displayName:current.displayName,genderApplicability:current.genderApplicability,purpose:current.purpose,lines:current.lines,active:true});render(<App controller={controller}/>);fireEvent.click(await screen.findByRole('button',{name:/more/i}));fireEvent.click(screen.getByText((_content,node)=>node?.tagName==='SUMMARY'&&Boolean(node.textContent?.includes('Male NSU · v2'))));expect(screen.getByText(/v2 · CURRENT/)).toBeInTheDocument();expect(screen.getAllByText(/^v1/).length).toBeGreaterThan(0);expect(screen.getAllByText(/Inventory item not configured/).length).toBeGreaterThan(0)})
  it('adds inventory through the signed controller path',async()=>{const controller=await setup();render(<App controller={controller}/>);fireEvent.click(await screen.findByRole('button',{name:/^Inventory$/i}));fireEvent.click(screen.getByRole('button',{name:/add item/i}));const form=screen.getByRole('form',{name:'Add inventory item'});fireEvent.change(within(form).getByLabelText('Item name'),{target:{value:'Test Belt'}});fireEvent.change(within(form).getByLabelText('Category'),{target:{value:'Accessories'}});fireEvent.change(within(form).getByLabelText('Initial on hand'),{target:{value:'12'}});fireEvent.click(within(form).getByRole('button',{name:'Add item'}));expect(await screen.findByText('Test Belt')).toBeInTheDocument();const state=await controller.technicalState();expect(state.inventory.some(item=>item.name==='Test Belt')).toBe(true);expect(state.events.filter(record=>record.event.eventType==='INVENTORY_ITEM_CREATED')).toHaveLength(1)})
  it('keeps draft counts local and submits exactly one event',async()=>{const controller=await setup();const initial=(await controller.project()).inventory[0];render(<App controller={controller}/>);await screen.findByText('Count with confidence.');fireEvent.click(screen.getByRole('button',{name:/add 1/i}));expect((await controller.project()).inventory[0].onHand).toBe(initial.onHand);fireEvent.click(screen.getByRole('button',{name:'Submit count'}));await waitFor(async()=>expect((await controller.project()).inventory[0].onHand).toBe(initial.onHand+1));expect((await controller.technicalState()).events.filter(record=>record.event.eventType==='INVENTORY_COUNT_SUBMITTED')).toHaveLength(1)})
  it('opens settings, persists personal preferences, and labels later features',async()=>{const controller=await setup(), local=storage(), settings=new LocalSettingsStorage(local);render(<App controller={controller} settingsStorage={settings}/>);fireEvent.click(await screen.findByLabelText('Settings'));fireEvent.change(screen.getByLabelText('Appearance'),{target:{value:'dark'}});fireEvent.change(screen.getByLabelText('Density'),{target:{value:'compact'}});fireEvent.change(screen.getByLabelText('Motion'),{target:{value:'reduced'}});expect(JSON.parse(local.values.get(SETTINGS_KEY)!)).toMatchObject({theme:'dark',density:'compact',motion:'reduced'});expect(screen.getByRole('button',{name:/Replay Tutorial/})).toBeDisabled();expect((await controller.technicalState()).events).toHaveLength(0)})
  it('restores settings from isolated preference storage',async()=>{const controller=await setup(),local=storage();local.setItem(SETTINGS_KEY,JSON.stringify({...DEFAULT_SETTINGS,textSize:'large'}));render(<App controller={controller} settingsStorage={new LocalSettingsStorage(local)}/>);fireEvent.click(await screen.findByLabelText('Settings'));expect(screen.getByLabelText('Text size')).toHaveValue('large')})
})
