import { describe, expect, it } from 'vitest'
import { DistributedAppController, bundleMapping } from './distributed/appIntegration'
import { inspectRepository } from './integrity'
import { MemoryRepository, migrateRepositoryState } from './storage/repository'
const storage=()=>{const values=new Map<string,string>();return{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>void values.set(key,value)}}
async function app(repository=new MemoryRepository()){const controller=new DistributedAppController(repository);await controller.initialize(storage());controller.setOnline(false);return controller}
describe('Stage 3A.5 cross-layer consolidation',()=>{
 it('persists cadets, Still Needed readiness, bundles and inventory across controller reloads',async()=>{const repository=new MemoryRepository(),first=await app(repository);const created=await first.createCadet({fullName:'Fictional Cadet',gender:'Female',nsLevel:'NS2',status:'ACTIVE'});const cadet=(await first.project()).cadets.find(c=>c.fullName==='Fictional Cadet')!;expect(cadet.cadetId).toBe(created.cadets.find(c=>c.fullName==='Fictional Cadet')!.cadetId);expect(cadet.cadetId).toMatch(/^cadet_/);const item=await first.createInventoryItem({name:'Mapped Shoe',category:'Footwear',variant:'10R',niin:'DEMO',onHand:2,reorderAt:1,countIncrement:1,active:true});const inventory=item.inventory.find(i=>i.name==='Mapped Shoe')!;await first.addStillNeeded({cadetId:cadet.cadetId,itemId:inventory.entityId,displayLabel:inventory.name,size:'10R',quantityNeeded:2,quantityFulfilled:0,status:'OPEN',firstNeededAt:'2026-01-01T00:00:00Z',source:'MANUAL'});expect((await first.project()).cadets.find(c=>c.cadetId===cadet.cadetId)?.readiness.status).toBe('INCOMPLETE');expect((await first.project()).stillNeeded.at(-1)?.availability.available).toBe(true);const bundle=(await first.project()).bundles[0],current=bundle.versions[0];await first.updateBundle(bundle.bundleId,{displayName:current.displayName,genderApplicability:current.genderApplicability,purpose:current.purpose,lines:current.lines,active:true});const second=await app(repository),projection=await second.project();expect(projection.cadets.some(c=>c.cadetId===cadet.cadetId)).toBe(true);expect(projection.inventory.some(i=>i.entityId===inventory.entityId)).toBe(true);expect(projection.bundles[0].versions).toHaveLength(2);expect(projection.stillNeeded).toHaveLength(3)})
 it('does not fabricate bundle mappings',async()=>{const controller=await app(),projection=await controller.project(),bundle=projection.bundles.find(b=>b.bundleId==='bundle-pt')!;expect(bundleMapping(bundle,projection.inventory)).toEqual({status:'UNMAPPED',mapped:0,total:3})})
 it('reports invariant and orphan failures without modifying records',()=>{const state=migrateRepositoryState({schemaVersion:3,events:[],outbox:[],inventory:[{entityId:'bad',name:'Bad',onHand:-1,issued:-2,version:0,appliedEventIds:['x','x']}],cadets:[],bundles:[{bundleId:'b',currentVersion:2,versions:[{version:1,eventId:'factory:x'},{version:1,eventId:'factory:x'}],appliedEventIds:[]}],stillNeeded:[{requirementId:'n',cadetId:'missing',itemId:'missing'}],conflicts:[]});const report=inspectRepository(state);expect(report.healthy).toBe(false);expect(report.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['NEGATIVE_ON_HAND','NEGATIVE_ISSUED','DUPLICATE_APPLIED_EVENT','ORPHAN_REQUIREMENT_CADET','ORPHAN_REQUIREMENT_ITEM','ORPHAN_BUNDLE_VERSION','DUPLICATE_BUNDLE_VERSION','DUPLICATE_FACTORY_BUNDLE']));expect(state.stillNeeded).toHaveLength(1)})
})
